### ISSUE TITLE
8/8 Gruul dies to Ragnaros at End of Turn (Aura Update (Health/Attack) only runs sometimes)

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#325] opened 2015-12-13 16:21 UTC
https://www.youtube.com/watch?v=Fhu4lSKKHfE&t=3m17s

Video from report made at http://us.battle.net/hearthstone/en/forum/topic/19288659063#14

In this video, the player plays a 7/7 Gruul which grows to 8/8. The opponent plays a Ragnaros, which proceeds to kill the 8/8 Gruul. The 8/0 Gruul then visibly triggers and dies instead of surviving as a 9/1. This goes against the rule that deaths are not checked until all simultaneous effects have completed, and reverts an old bug from last year.

Here, Ben Brode directly says that Gruul should survive a Ragnaros hit.

https://twitter.com/bdbrode/status/536531878354763776

> deaths happen after all triggers fire. This lets gruul save himself before he dies. KT should not be dead...

https://www.reddit.com/r/hearthstone/comments/2ni1w4/new_gvg_card_sabotage_epic_rogue_spell/cmdsgpt

>  We always wait for all effects to finish firing before cleaning up minions who are "dead".

Example of 8/8 Gruul surviving a Ragnaros attack: https://www.youtube.com/watch?v=JtTSETA5_Q8

I am unable to find any case of Gruul dying to Ragnaros since GvG until today.

**Comment by jleclanche** [comment] 2015-12-13 16:23
Is this 100% reproducible?

**Comment by Xinhuan** [comment] 2015-12-13 16:33
Probably, haven't tried yet - just wanted to track this with relevant links until we get to reproducing this.

Actually, I searched a bit, I can't even find any instance of Ragnaros killing Gruul ever, including before GvG.

**Comment by Patashu** [comment] 2015-12-14 00:44
tweeted @ywoo_dev: https://twitter.com/Patashu0/status/676200886528380931

**Comment by Patashu** [comment] 2015-12-19 07:25
Patashu and Xinhuan confirmed this bug for both dominant player orders. Video coming later today.

https://gist.github.com/Patashu/08ccd1ccdaf269675247

**Comment by 10925** [comment] 2016-01-18 06:31
Personally, I tested:
A 2 health Gruul would died with friendly Baron Geddon.
A 2 or less health Ethereal Arcanist (with player control secret) would also died with friendly Baron Geddon.
I think that's a bug about end of turn enhancement/ self buffing?
Maybe I need test Baron with Young Priestess and some 2 health minions?

**Comment by Patashu** [comment] 2016-01-18 09:17
You could also test Shade of Naxxramas and Lightwell (converted to damage by Auchenai Soulpriest), to see if the bug exists in the Start of Turn Phase.

**Comment by 10925** [comment] 2016-01-18 10:50
I and my friends used to test a 1 health Shade of Naxxramas with Nat Pagle and Sea Reaver(created by Gang Up).
It would alive and grow normally, and wouldn't die until the normal auto-draw that 2nd Sea Reaver.
So we think it's just a bug for end of the turn.

And forgot to say that enemy Baron could also kill 2 health Gruul.

**Comment by 10925** [comment] 2016-02-15 14:18
My old test seems forgot consider the play order.
I think the play order does matter. And here are video proofs.
Gruul(and Ethereal Arcanist) play first, then Baron, it would die:
https://www.youtube.com/watch?v=IIeDnqCnZlk&feature=youtu.be
But if you opposite the order:
https://www.youtube.com/watch?v=MnAAD0wQA6M&feature=youtu.be
they would alive as intended.

**Comment by Patashu** [comment] 2016-02-15 22:08
But that contradicts https://www.youtube.com/watch?v=ZdfcH6NMbx0&list=PLx2kRadCTuYYrck0V0soHYjBvas9dGDYI&index=75 , where regardless of whether Ragnaros or Gruul triggers first, Gruul dies.

Can you explain this contradiction? We have video of both...

**Comment by 10925** [comment] 2016-02-16 03:50
I cannot explain.
And with my friends tips,I tried this one:
https://youtu.be/oR7FmiH3hP8
as you can see, the Ethereal Arcanist died at the 2nd end of turn (same thing happen to gruul).
Probably relate to:
https://github.com/HearthSim/hs-bugs/issues/245

But it's also contradict to one of my old post:
https://www.youtube.com/watch?v=MnAAD0wQA6M&feature=youtu.be
they alive with the second time Baron burning.
Which means may be Emperor or some other end of turn effect would affect this interaction.

So, the only thing I can say now is the end of turn effect really became totally mess.

**Comment by PattuX** [comment] 2016-02-16 18:48
Random idea:
Maybe the bug behind #321 is the same that applies here. What I have in mind is that multiple instances of a self buff always apply at the end. That would mean the processing order is messed up really hard so that a self buff does not save a minion if it already has another instance of that self buff.

This is explaining https://www.youtube.com/watch?v=oR7FmiH3hP8&feature=youtu.be

but on the other hand contradicted by https://www.youtube.com/watch?v=MnAAD0wQA6M&feature=youtu.be (Gruul should have died, Arcanist should have survived)

**Comment by PattuX** [comment] 2016-02-17 02:44
Semms like there was indeed something to it: https://youtu.be/Yh3yvKPZ-G8 :)

**Comment by 10925** [comment] 2016-03-17 16:27
So I and my friend test almost all the timing that would self-buffing and takes damage at same time.
We conclude that this 4 timing would cause this bug.
1. At the start of turn(Use Auchenai Soulpriest + Lightwell + damaged Shade of Naxx):
https://www.youtube.com/watch?v=L-ykNeRo71g&feature=youtu.be

2. At the end of turn,we had proven it several times

3. Your hero takes damage,as https://youtu.be/Yh3yvKPZ-G8  shows.

4. And when a minion dies( Use Junkbot + Explosive Sheep)
https://youtu.be/p3bGa_M_iiU

Other timing that would not affect by the bug, we found 3.
1. (on) Play phase(enemy Knife Juggler + Troggzor the Earthinator vs Questing Adventurer)
Sorry i forgot to film this one.

2. Inspire Phase as  https://youtu.be/Yh3yvKPZ-G8 shows

3. And When you discard a card(Tiny Knight of Evil Vs Soulfire):
https://youtu.be/KWK1fmhzivw

**Comment by Patashu** [comment] 2016-03-17 22:10
Theories:

1) On Play Phase, it doesn't happen because Aura Update (Health/Attack) is scheduled to run due to the played card leaving your hand and entering play.

2) Inspire Phase, it doesn't happen because Aura Update (Health/Attack) is scheduled to run due to the Secret Dart Trap leaving play and entering the graveyard.

3) Discarding a card, it doesn't happen  because Aura Update (Health/Attack) is scheduled to run due to the discarded card leaving your hand and entering the graveyard.

My theory ATM is that Aura Update (Health/Attack) runs whenever an entity has been silenced, generated or has changed zones since the last time Aura Update (Health/Attack) ran. Can you think of any counterexamples (Aura Update (Health/Attack) without any of those 3 happening)?

**Comment by PattuX** [comment] 2016-03-18 03:29
In my mind the only thing causing Aura (A/H) to run is SHOW_ENTITY.

In all 4 bugged examples no entity is new to any of the players = no new entity (assumig self buff was already there).

1) Knife Juggler is revealed 

2) Dart Trap is revealed. (If we get some "Inspire: Deal x damage to all minions" we can try to kill Kvaldir without revealing a new entity)

3) Soulfire is revealed + not sure whether discarding causes revealing aswell.

Side note for a test: have self buff in Setaside (please not Murloc Tidecaller). Apply first instance of a self buff. Apply 2nd instance of self buff (both w/o revealing entites). Count Aura Updates in log.

**Comment by 10925** [comment] 2016-03-18 06:37
Hi, I just share with you of my friend idea:
I don’t think the self-buff bug is about Aura Update(H/A).We can see from the animations that the Floating Watcher had tried to buff himself before death.However,according to the Rulebook,Aura Update(H/A) runs before the Death Creation Step.If self-buff is during the Aura Update(H/A),the Floating Watcher should have buffed himself and survive the Death Creation Step,as opposed to the test results.

In fact,I’d like to define it as Enchantment Update.My theory is as follows:

Enchantment Update is divided into Usual Enchantment Update and Unusual Enchantment Update.
Usual Enchantment Update only runs when a normal phase and all the relevant Death Phases after it end.

Unusual Enchantment Update runs when a new entity(minions,cards or enchantments) is created or moves to the Play Zone or Graveyard Zone.

1.You have a 3/1 Questing Adventurer(self-buffed),and your enemy has a Troggzor the Earthinator and a Knife Juggler.You cast a spell,and the Knife Juggler hits your Questing Adventurer,but your Questing Adventurer is still 4/1 alive,due to the creation of a new minion.

2.You have a 5/4 Tiny Knight of Evil(self-buffed),and you cast Soulfire on it.It can still be 6/1 alive,due to discard(The card moves to the Graveyard).

3.You have a 6/4 Kvaldir Raider(self-buffed),and your enemy has a Dart Trap.You use your hero power,your Kvaldir Raider will be 8/1 alive,due to the secret moving to the Graveyard.

4.You have a 6/2 Floating Watcher(self-buffed) and a 5/4 Sylvanas,and your enemy has a 4/4 Abomination and a 4/4 Dancing Swords.You trade your Sylvanas with the Abomination.Your Floating Watcher will be 8/2 alive,due to the move of the Dancing Swords.
(10925: Here is the test video https://youtu.be/BUZvAj9lGFk）

Whether silence can lead to Enchantment Update is not sure.Maybe it’s true,for silence equals to removing all the enchantments.One test is to cast Mass Dispel when you have a 6/2 Floating Watcher(self-buffed),and draw a Flame Leviathan(hard to test as 3 class cards are involved).

**Comment by Patashu** [comment] 2016-03-18 10:26
(FYI, In https://youtu.be/BUZvAj9lGFk it's not clear if the Acolyte of Pain drawing a card or the Voidcaller changing controllers is what caused Floating Watcher to survive. They'd have to be tested individually.)

Hi 10925, thanks for all your investigation and analysis.

Just to be clear, the Advanced rulebook is not 100% accurate on these kinds of mechanics yet, since it was introduced in a recent change and appears to be a bug that we still don't fully understand. Notes:

1) While the Advanced rulebook does say that an Aura Update (A/H) will run before the Death Creation Step, my theory is that after the change that caused this bug, Aura Update (A/H) only runs if certain kinds of events have happened since the last Aura Update (A/H).
2) When an Enchantment is created and attaches to an Entity, it has an immediate effect - even before the next Aura Update (A/H) has run, stats will be updated. Some examples:
2a) The Lightbomb vs Frothing Berserker bug. https://github.com/HearthSim/hs-bugs/issues/133 (Note that Frothing Berserker used to take as many points of damage as he buffed, but now he just takes 3 if he was unbuffed even if he triggers many times, and the change happened around the same time this bug was introduced!)
2b) If you play Holy Wrath and a Shadowfiend triggers on the drawn card and reduces its cost by 1, you deal 1 less damage. https://www.youtube.com/watch?v=_rR99Z3sFAU But Auras do nothing. https://www.youtube.com/watch?v=SZNbVSMRTQA
2c) Some area of effect damage deathrattles ignore (don't damage further) mortally wounded (0 or less Health) minions. (Currently it's Explosive Sheep but it used to be Abomination, for example). If you stack on-death triggers AoE, Avenge, AoE and the Avenge buffs a mortally wounded minion, it is hit instead of ignored.
3) However, when an Enchantment is attached to a minion that already has that Enchantment, it doesn't create a new Enchantment Entity - it just updates the already existing one. (This might only be true for self-buffing minions, or it might be true for Enchantments in general, I forget.)
3a) Despite not making a new Enchantment, the new effect will be processed at the correct timing (for example, Attack Buff, Aldor Peacekeeper, Attack Buff produces the expected effect).

3 is the most important part - it means that a minion buffing itself for the first time creates a new Entity, meaning the next Aura Update (A/H) runs. But if it already had that buff, no new Entity is created, so something ELSE has to happen to ensure the next Aura Update (A/H) runs. It also means that the minion's stats won't be immediately updated.

I think your model (with the Enchantment Update terminology) and mine will produce the same results. But there's no need to introduce new terminology when we can just say that Aura Update (A/H) sometimes doesn't run.

Some suggested tests to try:

1) You have three minions, played in order: anything, 3/4 Frothing, 2/4 Frothing. Play Lightbomb. The first damage event will trigger 3/4 (but it won't be updated yet), then 2/4 (creating and attaching a new Enchantment). The moment this happens, will the 3/4 be updated to 4/4 and take 4 damage, or does attaching an Enchantment to an Entity only update that one Entity's stats?

2) Holy Wrath/Shadowfiend test again, but with two Shadowfiends. Is the damage reduced by 1 or by 2? Testing to see if the second instance of Shadowfiend cost reduction triggers an immediate update of the card's cost or not.

3) Will a second instance of Avenge/Anubisath Sentinel Deathrattle buffing a minion immediately update its stats? Make the next Aura Update (Health/Attack) run?

---

After writing this post I watched https://www.youtube.com/watch?v=p3bGa_M_iiU (Junkbot vs Explosive Sheep) again and I'm really confused. This basically breaks my theory from the previous post - the Explosive Sheep died and left play since the last Aura Update (A/H), but nothing happens. Why? We know that if a Stormwind Champion dies then his Aura will stop affecting minions the next Aura Update (A/H). So what's different between the two scenarios? (It also breaks your 'Unusual Enchantment Update' idea, by the way, since you said that a minion moving to the Graveyard should run it too)

**Comment by 10925** [comment] 2016-03-18 11:13
Hi, I just feed back your reply to my friend (the analysis' author is the opponent of  this video :https://www.youtube.com/watch?v=BUZvAj9lGFk
not me), i hope it would help his work.
By the way,  Acolyte of Pain drawing a card cannot save Floating watchers.
We did this test first, and I forgot to upload it.
https://www.youtube.com/watch?v=atx69wvYY4A&feature=youtu.be

**Comment by Patashu** [comment] 2016-03-18 22:50
OK, so not all kinds of Entity movement ensure the next Aura Update (A/H) runs. Drawing doesn't, discarding does, death doesn't (but what about Stormwind Champion dying, can anyone explain that?), controller change does (would have to for Stormwind Champion etc, I suppose). Being generated in play does. Being force played from hand does...? (untested I think?). Secret being revealed and leaving play does. The topdecked card being revealed might? (Flame Leviathan, minions that are revealed due to the Entomb/transform minions bug ( https://github.com/HearthSim/hs-bugs/issues/320 ) A card being generated in your hand might? (untested I think). How about in your deck? Bounced from play into hand? Bounced from graveyard to deck (Malorne)? Bounced from graveyard to hand (Anub'arak)?

Quite complicated...

**Comment by PattuX** [comment] 2016-03-20 17:14
To keep this up to date:
As we said, dying is not a reason to run the Aura Update (A/H).

Only certain entities moving to GY cause it to run, see [here](https://vid.me/k9P4). 

From [another test](https://vid.me/hW5j) we can conclude that not Stormwind Champion leaving play causes Aura (A/H) to run, but Stormwind Champion's buff on other minions. So if no other minions were affected by Stormwind's Aura, Aura Update (A/H) does not run, making Watcher die.

Sidenote: In the first video, Floating Watcher survives with 1 HP instead of 2. This is probably caused by the fact that HS detects that Floating Watcher's maximum health was not decreased (usually Stormwind leaving play causes this, but Watcher's buff makes max health increase by 2 at the same time) so it does not see the need to decrease damage on the minion. Might be worth its own ticket.

**Comment by 10925** [comment] 2016-03-21 13:21
Hello,my friend kybxd(which is the capital letter of each word for it's battle.net name)
bring some new idea:
Aura Update(Health/Attack) is divided into 3 aspects.

Rule 1:Conditional Self Aura Update(H/A),which runs in a phase.After an event ends,if a new enchantment entity is added to a minion,Aura Update(H/A) will run on it only.

Rule 2:Conditional Entire Aura Update(H/A),which runs after a phase but before the Death Creation Step.If a new entity(minions,cards or enchantments) is created or moves to the Play Zone or Graveyard Zone during the former phase,Aura Update(H/A) will run on all minions.
(Note:The removal of Stormwind Champion’s aura and other similar auras can trigger as ‘Deathrattle:Remove the aura from affected minions.’Therefore,if no minion is affected by the aura,it won’t be counted as an entity moving to the Graveyard.)

Rule 3:Guaranteed Entire Aura Update(H/A),which runs when a normal phase and all the relevant Death Phases after it end.Aura Update(H/A) will run on all minions.

Aura Update(Mana Cost) is partly different.
Rule 4:Conditional Self Aura Update(MC),which runs in a phase.After an event ends,if a new enchantment entity is added to a card,Aura Update(MC) will run on it only,similar to Aura Update(H/A).

Rule 5:Guaranteed Entire Aura Update(MC),which runs on two timings.One is after a phase but before the Death Creation Step,and the other is after the Death Creation Step but before the next phase.

The order of Aura Update between phases is as follows:
1.The former phase(Conditional Self Aura Update runs in it.)
2.Conditional Entire Aura Update(H/A) and Guaranteed Entire Aura Update(MC)
3.Death Creation Step
4.Guaranteed Entire Aura Update(MC)
5.Step 1-4 loop until no death
6.Guaranteed Entire Aura Update(H/A)

Examples of Rule 1:
1.You have any minion,4/4 Frothing Berserker I(self-buffed twice),and 2/4 Frothing Berserker II(unbuffed).You cast Lightbomb.Frothing Berserker I takes 4 damage,and Frothing Berserker II takes 3 damage.
(10925: https://youtu.be/R9dnoreiVwM)

2.You have any minion,2/4 Frothing Berserker,2/4 Frothing Berserker,2/4 Frothing Berserker,and 2/4 Frothing Berserker(all unbuffed).You cast Lightbomb.All Frothing Berserkers take 3 damage.
(10925:

Examples of Rule 2:
1.Explosive Sheep vs Junkbot.Only Explosive Sheep’s deathrattle triggers in the Death Phase,which doesn’t apply to Rule 2.Conditional Entire Aura Update(H/A) doesn’t run,and the Junkbot will die.
(10925:https://youtu.be/p3bGa_M_iiU)
2.Abomination+Floating Watcher vs enemy’s only Stormwind Champion.No minion’s Stormwind aura is removed,so Conditional Entire Aura Update(H/A) doesn’t run,and Floating Watcher will die.
(10925:https://vid.me/hW5j)

Example of Rule 3:
You have a 6/4 Floating Watcher(self-buffed),and your enemy has a Dart Trap.You use Warlock’s hero power.Floating Watcher won’t die from Dart Trap,proving Guaranteed Entire Aura Update(H/A) doesn’t need to wait until the whole sequence ends.

Example of Rule 4:
Your have two Shadowfiends.You cast Holy Wrath.The cost of the card you draw will be decreased by 2,and the spell will deal the decreased damage.This also proves several Shadowfiends’ Enchantments won’t be counted as one.
(10925:Sorry it's test by kybxd himself, I had no film)

Example of Rule 5:
1.All your minions are at full health.You trade your 1/1 Wisp with an enemy 1/1 Wisp.The change of Crush’s mana cost will be 7-3-7.
(10925:Sorry it's test by kybxd himself, I had no film)

2.All your minions are at full health(more than 3).You trade your 1/1 Explosive Sheep with an enemy 1/1 Wisp.The change of Crush’s mana cost will be 7-3-7-3.
(10925:Sorry it's test by kybxd himself, I had no film)

**Comment by Patashu** [comment] 2016-03-22 01:38
Thank you for your and kybxd's further investigations and discussions.

Wow, I think rule 5 example 2 is the most interesting. I didn't even realize mana cost updates are MORE common than health/attack updates or think to test it. This is definitely something that warrants further investigation. (Another thing is that I bet attaching a new Mana Cost Enchantment to a card is enough to trigger the next Aura Update (Health/Attack) - even though it's not displayed in the log, such acts do create a new Entity.)

Thank you for rule 4 example. It sounds like only self-buffs stack, and all other kinds of buffs (Avenge, Anubisath Sentinel, Shadowfiend, Emperor Thaurissan, etc) won't stack.

Thank you for rule 1 example 1 as well. So when a minion's stats update due to an enchantment attaching, nothing else updates.

Rule 3 example is also good.

I also know of another interesting example - when Preparation's Enchantment triggers to end, the mana cost of the played spell changes immediately, for the purposes of things such as Summoning Stone. https://github.com/HearthSim/hs-bugs/issues/273 But I don't know if this is a special case or if it fits into a larger model.

But in your model, don't forget the Sylvanas test. Also, there needs to be a distinction made between outermost Phases that proceed to a Death Phase and ones that don't - is it correct to say that the guaranteed Aura Update (H/A) only runs if there is NO Death Phase afterwards? (e.g. it runs just before we would have proceeded to a Death Phase, only if we don't) So then discarding a card (Soulfire/Tiny Knight of Evil) and revealing a Secret (Kvaldir Raider/Dart Trap) are actions that ensure next Aura Update (H/A) will run, before deaths are created.

PattuX hypothesized that the act of revealing an Entity might be one thing that causes next Aura Update (H/A) to run. You can test this with things like drawing Flame Leviathan/Sea Reaver, Joust effects like The Skeleton Knight, discarding cards, drawing a card but milling it due to a full hand, revealing/destroying Secrets, force playing a minion from your deck (Deathlord, Varian Wrynn, Desert Camel, Ancestor's Call), force playing a minion from your hand (Alarm-o-Bot, Voidcaller).

It's interesting that minions dying and leaving play doesn't in general run next Aura Update (H/A), only if they have a H/A Aura that was affecting one or more minions.

Finally, Silence is probably the last event that will run the next Aura Update (H/A).

**Comment by Kybxd** [comment] 2016-04-15 12:08
I have found new evidence for the above idea of Aura Update.

1.Naga vs Shadowstep+Dread Corsair(https://youtu.be/N_udZsNOf6s)
Naga>Shadowstep>Corsair,and the final mana cost is 5-2-1=2.
Dread Corsair's return to hand is counted as an entity's movement,so the Aura Update runs first.

2.Naga vs Far Sight(https://youtu.be/N_udZsNOf6s)
Far Sight>Naga,and the final mana cost is 5.
Drawing a card is not counted as a timer for Aura Update,so the Aura Update doesn't run until the phase ends,later than Far Sight's mana cost -3.

**Comment by PattuX** [comment] 2016-04-15 14:03
I think the first example is another topic we cover in this video: https://www.youtube.com/watch?v=RNrXJGFETXw
Note that the processing order does not rely on which enchanment was detected in which Aura Update, but on the timestamp on the enchantment.

We also covered the second example in the video but I'm still not sure why this happens and why it only happens with Far Sight and Call Pet but not with Shadowfiend. As both, Far Sight and Shadowfiend, apply an enchantment, there is no way both triggers can fit the same model.

**Comment by PattuX** [comment] 2016-04-17 02:09
Tested 4.3 with Watcher + Abom

**Comment by Patashu** [comment] 2016-06-04 00:51
PattuX has recorded two interesting videos.

https://www.youtube.com/watch?v=du-zmRiLjrU shows that it is possible for a Dire Wolf Alpha's Aura to update (I think) after the Death Creation Step and before the following Death Phase, and this also doesn't make a recently deceased Stormwind Champion update.

https://www.youtube.com/watch?v=1kPtXOcdVO0 (see log) shows that it is possible for Goblin Sapper to update between the Death Creation Step and before the following Death Phase, a timing we previously thought impossible for Aura Update (H/A) to run.

**Comment by PattuX** [comment] 2016-06-04 00:57
Addition: It is important that the card is not drawn in the Death Phase after the Combat Phase. Something in the Combat Phase causes the Conditional Aura Update to run, so we dont get to see the effect that Sapper is not updated until the weird Aura Update between DCS and Death phase.

**Comment by Patashu** [comment] 2016-06-04 23:21
Confirmed in 5.0.0.103 by standard method: http://us.battle.net/hearthstone/en/forum/topic/20745094688

**Comment by culinko** [comment] 2016-08-16 04:27
Confirmed in 6.0: https://www.reddit.com/r/hearthstone/comments/4xve6s/a_bug_in_effect_ordercard_text_not_being_correct/.

**Comment by Kybxd** [comment] 2017-07-24 12:42
Another proof for revealing an Entity causing Aura Update: Daring Reporter vs Flame Levithan (Priest's Reporter died because of  Dorminant Player Bug)
* https://youtu.be/L3LHfYT9Rbk

**Comment by PattuX** [comment] 2017-07-24 16:31
How do you make sure Aura (A/H) ran and why should Dominant Player Bug make Daring die (there's no Death Phase between Dominant/Secondary Plaer's queue)?

And also I'm still not sure what they did to make 1HP Daring survive Mortal Coil, so make sure you know how it works when you want to use it for proofs.

**Comment by Kybxd** [comment] 2017-07-25 01:05
Daring Reporter cannot buff itself when it's mortally wounded, similar to Grim Patron. (#638) 

Rule DC2 says draw-a-card effects is always earlier than draw-this effects, but exactly this is because Play Queue is earlier than Hand Queue. So whether Flame Levithan or Daring Reporter's ability is resolved first is still decided by DP bug. It can also be seen that Priest's Reporter's ability fails to flash in the video.

Mage's Reporter's ability flashes, then Flame Levithan deals 2 damage to it. If there wasn't some kind of Aura Update, it should have died just like the 8/8 Gruul dying to Ragnaros.

**Comment by PattuX** [comment] 2017-07-25 15:16
I had this in mind: https://www.reddit.com/r/hearthstone/comments/6kzisr/til_acolyte_daring_reporter_volcano_interaction/

But after looking at it again it makes sense: If Acolyte is hit before Daring is dead she will trigger (while alive), but the enchantment will only be updated in the next Aura (A/H) after Volcano resolved, saving her from dying.

So you're right, your test is good, thanks :)

**Comment by Kybxd** [comment] 2017-07-26 05:05
I tested unbuffed Reporter and it fits our model. (In video II the opponent only drew 2 cards, and one was milled.)
* https://youtu.be/Z5UG6n_2EHY
* https://youtu.be/iyajn-7d-Xc

Besides, there is no factor causing the next Aura Update to run in the above-mentioned situation, but the Reporters do survive. I also tested this:
* https://youtu.be/rycsrDjCMm4

So I think the skipping of Aura Update before Death Creation Step only exists in some phases. These are: Start/End of Turn Phase, and Death Phase.

**Comment by Kybxd** [comment] 2017-12-03 16:14
I retested self-buff bugs and these are fixed ones: Geddon + Ethereal Arcanist, Explosive Sheep + Junkbot, Auchenai + Lighewell + Shade of Naxx
https://youtu.be/uqmJSAS_dsA

Gruul vs Ragnaros is also fixed but I didn't record it. 
Not fixed: Daring Reporter vs Acolyte + Volcano, Reporter remains alive as a 6/2. (Sometimes it can be killed because of damage order.)

A new bug (I guess it's related to this issue): Imp Gang Boss + Crypt Lord at 1 health + Defile. If Crypt has never buffed itself, Defile will end immediately it deals the first AoE damage, and Crypt remains alive. Else Defile will repeat and clear the board.
https://www.bilibili.com/video/av16851830/#page=2

**Comment by PattuX** [comment] 2017-12-03 17:31
Thanks for testing.

Technically the Sheep + Junkbot evidence is not valid tho, as we know this bug does not happen after combat phase (only start/end turn and death phase so far). You'd need to kill a Tentacle of N'Zoth or have a Geddon kill your sheep which then reduces the Junkbot to 0. But seeing the others being fixed I'm sure this is as well. All other tests are good.

The Crypt Lord seems to be the exact same issue as Daring.

So I guess the core of this thread (Aura Update not running after certain phases when no entity entered the board) is fixed. 

The issue remaining is that enchantments are attatched immediately, however further instances of the same enchantment are only processed in the aura update, which can make minions uneligible for random damage. Not sure whether thats a new ticket, we'll see.

**Comment by Patashu** [comment] 2017-12-03 21:22
The remaining bug is getting into may-be-intended territory, since it’s harder to discover and hard for them to fix with the model they use for HS. It doesn’t feel intuitive though, that’s for sure.

**Comment by Kybxd** [comment] 2018-04-20 06:14
Fixed: Imp Gang Boss + Crypt Lord at 1 health + Defile (Now Crypt Lord doesn't trigger when mortally wounded)
Not Fixed: Howlfiend +Knight of the Evil at 1 health + Defile
Not sure: Daring Reporter vs Acolyte + Volcano

Another interesting discovery:
You have Kobold Barbarian and unbuffed 2-Attack Gurubashi Berserker, enemy has Misdirection and Explosive Trap. At the start of your turn Kobold attacks enemy hero but is misdirected to Gurubashi. Then Explosive Trap damages the Gurubashi to 5 Attack.  And Gurubashi deals 5 Combat Damage to Kobold.

But if the Gurubashi is a buffed 5-Attack one, Explosive Trap should damage the Gurubashi to 8 Attack. But as aura is not updated, Gurubashi still deals 5 Combat Damage to Kobold.

**Comment by PattuX** [comment] 2018-04-20 09:14
Reworked to #934

**Closed by PattuX** 2018-04-20 09:14 UTC
Labels: gameplay
