### ISSUE TITLE
Attempting to use non-targetable hero powers as turn expires will flip the hero power coin in the UI but not activate the hero power

### ISSUE THREAD

**Issue by theAprel** [HearthSim/hs-bugs#341] opened 2016-01-02 03:16 UTC
![hearthstone screenshot 01-01-16 21 53 32](https://cloud.githubusercontent.com/assets/10458225/12073034/02a1d722-b0d4-11e5-9b9e-ef1cfc66d2c3.png)

The hero power coin remains in the "used" state even after the start of the player's next turn, but it is selectable. Once the hero power is selected and used, the UI's behavior returns to normal. This was observed in the boss hero power tavern brawl but probably happens in any game mode, though it may require a refreshable hero power such as with Garrison Commander or Coldara Drake.

To reproduce, wait till close to end of turn with a non-targetable hero power that can be used more than once, click the hero power coin and keep spamming left-click while the animation plays and turn timer expires.

**Comment by Xinhuan** [comment] 2016-01-02 03:24
Duplicate of #162.

**Closed by Xinhuan** 2016-01-02 03:24 UTC
Labels: animations
