### ISSUE TITLE
Waggle Pick does not reduce the cost of minion that was generated from a Deathrattle

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1171] opened 2019-05-04 12:24 UTC
https://us.forums.blizzard.com/en/hearthstone/t/known-issues-list-2019-updated-april-25th/64/6

> Waggle Pick does not reduce the cost of minion that was generated from a Deathrattle

**Comment by Jetz72** [comment] 2019-05-06 12:40
Duplicate of #1144.

**Closed as completed by Jetz72** 2019-05-06 12:40 UTC
Labels: duplicate
