### ISSUE TITLE
Reincarnate intercepted by Spellbender does not trigger Effigy or Duplicate

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#125] opened 2015-08-29 02:23 UTC
When your opponent casts Reincarnate and your Spellbender intercepts, your Effigy will not trigger.
* http://imgur.com/a/0s3hJ

If reincarnate is not intercepted by the secret, Effigy does trigger.
* http://imgur.com/a/NMssY

Reincarnate intercepted by Spellbender also does not trigger Duplicate. Lightning Bolt into Spellbender does trigger Effigy though:
* http://imgur.com/a/z3wd8

So the bug seems to be specifically Reincarnate triggering Spellbender.
* https://www.reddit.com/r/hearthstone/comments/3iqdj2/possible_bug_reincarnate_on_spellbender_doesnt/

(Note that letting Spellbender proc, then casting Reincarnate on the token directly works fine. Tested by Culinko.)

**Comment by jleclanche** [comment] 2015-08-29 06:56
Does effigy trigger on wisp/target dummy?

**Comment by Patashu** [comment] 2015-08-29 09:05
In IRC it was claimed that Effigy triggers on Mirror Image. The bug seems to be specifically with Reincarnate and Spellbender, which is super weird.

Or possibly it's to do with Reincarnate and the target doesn't matter...

**Comment by culinko** [comment] 2015-08-30 18:05
I confirmed it with Reincarnating a 4-drop and the Duplicate didn't trigger because of the Spellbender secret.

**Comment by culinko** [comment] 2015-09-02 00:13
I also tested reincarnating just the Spellbender token and it worked just fine. So maybe you should change the title of this issue and the first sentence, because it's related to the secret Spellbender, not the token.

**Comment by Patashu** [comment] 2015-09-02 03:07
Good find, culinko. I've edited the title and contents of the bug to reflect that.

**Comment by Patashu** [comment] 2015-12-06 07:07
Still happens in Patch 4.1. Made video and log, will upload later.

**Comment by culinko** [comment] 2016-04-03 13:53
Fixed in 4.2. Tested both Effigy and Duplicate.

**Closed by culinko** 2016-04-03 13:53 UTC
Labels: gameplay

**Comment by Patashu** [comment] 2016-04-03 21:31
This probably got fixed as a side-effect of the Forced Death Phase changes. Therefore, if the Forced Death Phase changes reverts, re-test this.
