### ISSUE TITLE
Decks Assemble! brawl rule does not run on-draw triggers

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#299] opened 2015-12-02 23:23 UTC
Cards drawn by the Decks Assemble! brawl rule do not run on-draw triggers such as The Mistcaller and Chromaggus:

* https://www.reddit.com/r/hearthstone/comments/3v771y/psa_the_mistcaller_battlecry_has_no_effect_in_the/
* https://www.reddit.com/r/hearthstone/comments/3v771y/psa_the_mistcaller_battlecry_has_no_effect_in_the/cxl0tnp?context=3

And if the card has an on-draw trigger, like Burrowing Mine, it does not run:

* https://www.reddit.com/r/hearthstone/comments/3v7fhi/how_iron_juggernaut_works_in_this_weeks_brawl/

*
![image](https://cloud.githubusercontent.com/assets/666597/11547588/3cd06612-99a9-11e5-985a-9073c4fddcab.png)

**Comment by Patashu** [comment] 2015-12-02 23:49
This might not be a bug, BTW. The specific word the game uses is 'redraw'. It's unclear if 'redraw' effects are intended to run on-draw triggers (like 'draw') or not (like 'put', 'add', 'generate')

**Comment by jleclanche** [comment] 2015-12-03 02:48
This is not a bug - and if it is, it's a duplicate of the other on-draw issue.

**Closed by jleclanche** 2015-12-03 02:48 UTC
Labels: !wiki, brawl
