### ISSUE TITLE
Spreading Madness/C'Thun/Disciple of C'Thun random visual bug where dark splash does not appear on the target

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#514] opened 2016-05-07 11:39 UTC
It is unknown what causes it to happen, but has been seen multiple times.

* https://youtu.be/7hv4KBRBkTI

**Comment by culinko** [comment] 2016-05-07 11:55
Dupe of #436.

**Closed by culinko** 2016-05-07 11:55 UTC
Labels: duplicate
