### ISSUE TITLE
Enrage effects have a priority earlier than all other Enchantments

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#252] opened 2015-11-11 22:36 UTC
Previously, Enrage Enchantments would be processed in play order - for example if you Aldor/Enrage a minion it has 1+(enrage effect) attack, but if you Enrage/Aldor a minion, it has 1 attack. In addition, un-Enraging and re-Enraging a minion would create a new Enrage Enchantment with new play order.
* https://www.youtube.com/watch?v=StimopyMMsA

However, as of Patch 4.0.0.10833 (LoE patch), the Enrage Enchantment always has priority earlier than all other Enchantments. For example, if a minion is Aldored then Enraged, it has 1 Attack still, and if a minion is Reversing Switched then Enraged, the Enrage does not change the minion's Attack. It is not clear if this is a bug or an undocumented change to the Enrage mechanic.
* http://us.battle.net/hearthstone/en/forum/topic/19650246493
* http://us.battle.net/hearthstone/en/forum/topic/19866686515
* https://www.reddit.com/r/hearthstone/comments/3sgi7o/bug_enrage_no_longer_boosts_attack_after_a/
* https://www.youtube.com/watch?v=VY_lcxMQocE
* https://www.youtube.com/watch?v=geIXizhhE4s

**Comment by liujimj** [comment] 2015-11-12 02:35
Should it be a bug? One can argue that the persistent Enrage is more mechanically consistent, if not consistent with the lore of a creature getting angry.

**Comment by Patashu** [comment] 2015-11-12 03:50
liujimj, I'd argue it's a bug because it's the following:

1) You can either imagine Enrage as being a trigger that puts an Enchantment on the minion, or an aura that checks to see if the minion's current health is lower than its maximum health every time auras update, and turns on if so.

1a) In the Enchantment case, when you damage an Aldored/Swapped minion, its Enrage Enchantment should have the most recent play order, and thus should be processed last.

1b) In the Aura case, Auras update to be after all Enchantments every Aura Update (Health/Attack) Step, so it should be processed after Aldor/Swap in such a case too.

The way Enrage works in 4.0 makes it mechanically like nothing else that exists in Hearthstone. (Note that there is one Mana Cost Aura, Summoning Portal, that has a special priority that puts it before all other Mana Cost changing effects, but there is no equivalent to this priority for Health/Attack prior to 4.0.)

**Comment by liujimj** [comment] 2015-11-12 05:13
I imagined it to be an Enchantment that is only applied once, so once it's on the stack below the Aldor, it just stays there.

**Comment by Patashu** [comment] 2015-11-12 05:57
Even in your mental model, you'd agree that if a minion is Aldored then Enraged the effects should apply in that order, and this isn't what we see in 4.0.

**Comment by Xinhuan** [comment] 2015-11-12 16:45
liujimj is saying that in his model, the enchant is applied once when the minion is summoned.

The enchant's value is dynamic. It is +0/+0 initially, and the buff updates itself to +2/+0 and changes back when necessary. This would mean that there is no need to constantly add/remove the buff. This new model might actually be more efficient code and cpu-wise, but the programmers might not realize the ramifications of such a change in code.

**Comment by PattuX** [comment] 2015-11-12 18:43
The only thing I can imagine is that enrage stat buffs are always applied first which might be caused by the fact, that this is no extern buff, rather than a self-buff and they changed the order for some reason (like Redemption always triggering last to avoid Deathrattle issues).

My very vague guess, is that it might have something to do with Keeper of Uldaman as it is the first card that changes Health and Attack at the same time and the first card which changes a minions health, but not to 1 (like Equality and Hunters Mark).
Actually I have some programming knowledge and can code myself but I'm not really into the HS code with those specific Enrage cases, but maybe someone else can use that idea.

**Comment by Xinhuan** [comment] 2015-11-12 19:27
Another video (angry chicken): https://youtu.be/geIXizhhE4s

(from https://www.reddit.com/r/hearthstone/comments/3sjthq/new_angry_chicken_enrage_bug/)

**Comment by PattuX** [comment] 2015-11-12 19:46
Equality does not enable this bug (or new mechanic).

(will edit proof)

**Comment by Patashu** [comment] 2015-11-12 22:10
PattuX: Yeah, that's not surprising, since Equality doesn't set the Attack of a minion to anything.

**Comment by CharlonTank** [comment] 2015-12-03 16:41
Can someone explain me this : 
amani berserker 2/3
crazed alchemist on amani berserker 3/2
ping the amani : 3/1 ???????? WTF

**Comment by Patashu** [comment] 2015-12-03 22:03
CharlonTank: That's exactly what this bug is doing, yes.

**Comment by Patashu** [comment] 2015-12-06 01:28
Confirmed as bug by yong woo! https://twitter.com/ywoo_dev/status/673312116040794112

**Comment by PattuX** [comment] 2016-03-14 21:07
Fixed in 4.2

Tested Humility, Aldor, Crazed Alchemist and healing up after modifying attack.

**Closed** 2016-03-14 21:07 UTC
Labels: gameplay
