### ISSUE TITLE
Siege Engine causes armouring animation to play twice

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#96] opened 2015-08-24 06:19 UTC
If you have Siege Engine in play and use Armor Up! or play Shield Block, the armor gain animation plays twice.
http://www.reddit.com/r/hearthstone/comments/3hb803/magni_siege_engine_causes_double_hero_power/

**Comment by NightKev** [comment] 2015-08-25 23:34
This is just one of many examples of the "double animation" bug, isn't it?

**Comment by Patashu** [comment] 2015-08-26 00:32
I thought the 'double animation bug' wasn't a generic bug, but that some animations had it and others don't. For example, you using Truesilver Champion is ok, but an enemy using Truesilver Champion lifts up a second time.

**Comment by jleclanche** [comment] 2015-08-26 01:29
It's possible some animations aren't affected, but I think the root cause is the same.

**Comment by culinko** [comment] 2015-08-26 08:04
In the Truesilver case, the opponent's attack animation is doubled even if they hit your face and there are no minion triggers in between. But I agree that Siege engine + armor, Lightbomb + on-damage minions and Nat Pagle fishing twice because of fatigue are the same bugs.

**Comment by culinko** [comment] 2015-08-26 17:39
Also, https://www.reddit.com/r/hearthstone/comments/3har11/til_playing_knife_juggler_and_then_dark_wispers/ should be the same bug then, right?

**Comment by NightKev** [comment] 2015-08-27 06:18
Yeah, I'd say so.

**Comment by culinko** [comment] 2015-08-27 10:26
Actually, the Nat Pagle case is a little bit different, because his lightning icon trigger flashes twice, interrupted by an animation. But the 3 examples + Knife Juggler one are in fact animation playing twice, interrupted by a lightning icon trigger.

**Comment by culinko** [comment] 2015-08-27 14:22
Duplicate issue, merged into #11.

**Closed by culinko** 2015-08-27 14:22 UTC
Labels: display, duplicate
