### ISSUE TITLE
Jaraxxus' INFERNO! sound plays again for each Knife Juggler hit that triggers on its summon

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#210] opened 2015-11-06 22:13 UTC
The sound effect of Jaraxxus' INFERNO! plays again for each Knife Juggler that triggers on Inferno's summon. Both players in the game can hear this bug.
* http://www.reddit.com/r/hearthstone/comments/2rmp4y/til_infernal_ft_knife_juggler/
* https://www.youtube.com/watch?v=CLVmkKw1oCU

**Comment by jleclanche** [comment] 2015-11-09 23:55
This is the multiple-animation bug.

**Comment by jleclanche** [comment] 2015-11-09 23:55
Dupe of #11

**Closed by jleclanche** 2015-11-09 23:55 UTC
Labels: audio
