### ISSUE TITLE
Ancient Curse and Burrowing Mine don't benefit from Spell Damage

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#493] opened 2016-05-01 23:54 UTC
Hallazeal heals the damage of Ancient Curse and Burrowing Mine triggering. However, these aren't considered to be spells resolving - we know because neither player's spell damage increases how much damage it does, and because the actual effect of the spell (if you get one into your hand and play it) is nothing. Essentially, 'deal damage and draw a card' is an on-draw trigger attached to the card, not the card's spell effect itself.
- https://www.reddit.com/r/hearthstone/comments/4gtba4/hallazeal_nullifies_ancient_shade/
- https://www.reddit.com/r/hearthstone/comments/4h91vl/perfect_counter/

He also heals Cursed! from Curse of Rafaam:
- https://www.reddit.com/r/hearthstone/comments/4ixlv5/til_hallazeal_complete_counters_curse_of_rafaam/

**Comment by Patashu** [comment] 2016-05-01 23:58
On the other hand, maybe this is not a bug? Fist of Jaraxxus when discarded benefits from spell damage, and presumably also benefits from Hallazeal.

https://www.youtube.com/watch?v=DFhDAfWH6Y4

But it seems inconsistent. Why does it not benefit from spell damage BUT counts as a spell anyway?

**Comment by Patashu** [comment] 2016-05-12 00:10
He also heals Cursed! from Curse of Rafaam:

https://www.reddit.com/r/hearthstone/comments/4ixlv5/til_hallazeal_complete_counters_curse_of_rafaam/

**Comment by jleclanche** [comment] 2016-05-12 00:23
None of this is a bug unless you can confirm it with Ben Brode, tbh.

**Comment by troggnostupidhs** [comment] 2017-06-12 19:33
Also with Kalimos 

https://www.youtube.com/watch?v=twMdosAkdBA&feature=youtu.be&t=2m31s

**Comment by VoidMayonnaise** [comment] 2017-06-13 15:13
https://youtu.be/aEENthYgXIU
Confirmed in 8.2.

**Comment by troggnostupidhs** [comment] 2017-08-09 02:49
Potentially fixed, at least with Kalimos

https://www.reddit.com/r/hearthstone/comments/6sg6jc/the_new_patch_nerfed_hallazeal_and_kalimoss/

**Comment by troggnostupidhs** [comment] 2017-08-10 03:47
Kalimos change confirmed by Toast

https://youtu.be/30SUCFoVIjk?t=4m

**Comment by troggnostupidhs** [comment] 2017-08-10 13:40
Still heals with Ancient Curse. Also tested spell damage and Ancient Curse is not affected  by it.

Deck
AAEBAaoIAu0Fwq4CDr0B+wGcArQC9QT+BbkG8RHRE/lG96oC+aoC+6oCx8ECAA==

![hearthstone screenshot 08-10-17 09 35 48](https://user-images.githubusercontent.com/22508641/29172914-841b130a-7daf-11e7-8b59-361e1afdbb2c.png)

![hearthstone screenshot 08-10-17 09 36 21](https://user-images.githubusercontent.com/22508641/29172961-ac4a4954-7daf-11e7-9f9d-544327aaef18.png)

**Comment by troggnostupidhs** [comment] 2017-11-19 17:27
https://youtu.be/xxmD2r3FSCM?t=455

**Comment by Kybxd** [comment] 2017-12-12 15:00
Now this issue might be changed to 'Ancient Curse and Burrowing Mine don't benefit from Spell Damage', since their card texts are changed.

Another strange interaction: I played Ancient Curse from hand at less than 7 health, and I died (shouted) immediately after taking 7 damage without drawing a card or fatigue. However, my Atiesh still worked and summoned a minion.

**Comment by troggnostupidhs** [comment] 2017-12-12 20:00
What are the new card texts?

**Comment by troggnostupidhs** [comment] 2017-12-12 22:23
Seems to be

> Ancient Curse
> You take 7 damage. Draw a card. Cast this when drawn.

> Burrowing Mine
> You take 10 damage. Draw a card. This explodes when drawn.

**Comment by troggnostupidhs** [comment] 2017-12-12 22:27
So do these cards do something now if played from hand?

**Comment by troggnostupidhs** [comment] 2018-11-03 20:34
It's possible this is intended because those cards have ImmuneToSpellpower

**Comment by troggnostupidhs** [comment] 2018-11-03 20:51
I'm reverting to the old ticket and closing. That tag makes it seem intentional for all of the autocast cards.

**Closed** 2018-11-03 20:55 UTC
Labels: invalid
