### ISSUE TITLE
Enemy attacks with Truesilver Champion repeats the 'lifting up' animation

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#98] opened 2015-08-24 06:20 UTC
When an opponent attacks with Truesilver Champion, his portrait visibly lifts off the board twice, once before the healing trigger and once after it.
https://www.youtube.com/watch?v=ClJfdopzsU8

**Comment by jleclanche** [comment] 2015-11-15 05:03
Didn't we say this was #11?

**Comment by culinko** [comment] 2015-11-15 09:40
It only happens for one player, though.

**Comment by jleclanche** [comment] 2015-11-15 09:50
We decided this was a dupe of #11.

**Closed by jleclanche** 2015-11-15 09:50 UTC
Labels: animations
