### ISSUE TITLE
Twillight's Call can sometimes resurrect minions given a Deathrattle via enchantment

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#869] opened 2017-12-17 06:08 UTC
Twillight's Call can summon Silverware Golem

Very likely this is because Silverware Golem has the tag ```InvisibleDeathrattle```

https://www.reddit.com/r/hearthstone/comments/7kbetc/twillights_call_summons_silverware_golem_intended/
  
![image](https://user-images.githubusercontent.com/22508641/34583903-8a131a38-f167-11e7-88ad-c57af6abd762.png)

**Comment by troggnostupidhs** [comment] 2018-01-04 19:11
With multiple tests, I was not able to reproduce this.

- Discarding doesn't do it. It's also not a tooltip issue.

![image](https://user-images.githubusercontent.com/22508641/34579878-d3ce0322-f158-11e7-8440-fe48e0bb8062.png)

![image](https://user-images.githubusercontent.com/22508641/34579884-d933f59c-f158-11e7-91e7-37eb2bb2b623.png)

- Milling doesn't work.

![image](https://user-images.githubusercontent.com/22508641/34579966-190be47c-f159-11e7-8124-a92c417a0ff5.png)

![image](https://user-images.githubusercontent.com/22508641/34579968-1ca9e994-f159-11e7-9f35-7fca8a139d48.png)

**Comment by troggnostupidhs** [comment] 2018-01-04 20:55
The screenshot in the original report is not very clear, it could possibly be a sidebar issue like #748

**Comment by VoidMayonnaise** [comment] 2018-02-28 14:56
I think we should close the issue since we cannot reproduce it. It should be a joke.

**Comment by Jetz72** [comment] 2019-02-01 04:06
I encountered something similar to this in Rumble Run. My Shrine had a Deathrattle added to it by a passive, and Twilight's Call resurrected it:

https://hsreplay.net/replay/i9Z2ktLyPuQnvCFQCiVW8g#turn=6a

Examination of the logs showed that when a Shrine dies with an added deathrattle, the DEATHRATTLE tag is not cleared.

Normal minion with added Deathrattle dying:
```
BLOCK_START BlockType=DEATHS Entity=GameEntity EffectCardId= EffectIndex=0 Target=0 SubOption=-1 
    TAG_CHANGE Entity=Zentimo tag=NUM_MINIONS_PLAYER_KILLED_THIS_TURN value=1 
    TAG_CHANGE Entity=GameEntity tag=NUM_MINIONS_KILLED_THIS_TURN value=1 
    TAG_CHANGE Entity=[entityName=Prince Keleseth id=102 zone=PLAY zonePos=4 cardId=ICC_851 player=2] tag=1068 value=4 
    TAG_CHANGE Entity=[entityName=Prince Keleseth id=102 zone=PLAY zonePos=4 cardId=ICC_851 player=2] tag=1068 value=0 
    TAG_CHANGE Entity=[entityName=Prince Keleseth id=102 zone=PLAY zonePos=4 cardId=ICC_851 player=2] tag=ZONE_POSITION value=0 
    TAG_CHANGE Entity=[entityName=Prince Keleseth id=102 zone=PLAY zonePos=4 cardId=ICC_851 player=2] tag=ZONE value=GRAVEYARD 
    TAG_CHANGE Entity=Zentimo tag=NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_TURN value=1 
    TAG_CHANGE Entity=Zentimo tag=NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_GAME value=3 
    HIDE_ENTITY - Entity=[entityName=Primal Talisman id=212 zone=PLAY zonePos=0 cardId=LOOT_344e player=2] tag=ZONE value=PLAY
    TAG_CHANGE Entity=[entityName=Primal Talisman id=212 zone=PLAY zonePos=0 cardId=LOOT_344e player=2] tag=ZONE value=REMOVEDFROMGAME 
    TAG_CHANGE Entity=[entityName=Prince Keleseth id=102 zone=PLAY zonePos=4 cardId=ICC_851 player=2] tag=DEATHRATTLE value=0 
    TAG_CHANGE Entity=[entityName=Prince Keleseth id=102 zone=PLAY zonePos=4 cardId=ICC_851 player=2] tag=DAMAGE value=0 
BLOCK_END
```
Shrine with added Deathrattle dying:
```
BLOCK_START BlockType=DEATHS Entity=GameEntity EffectCardId= EffectIndex=0 Target=0 SubOption=-1 
    TAG_CHANGE Entity=Zentimo tag=NUM_MINIONS_PLAYER_KILLED_THIS_TURN value=1 
    TAG_CHANGE Entity=GameEntity tag=NUM_MINIONS_KILLED_THIS_TURN value=1 
    TAG_CHANGE Entity=[entityName=Tribute from the Tides id=115 zone=PLAY zonePos=3 cardId=TRLA_154 player=2] tag=1068 value=4 
    TAG_CHANGE Entity=[entityName=Tribute from the Tides id=115 zone=PLAY zonePos=3 cardId=TRLA_154 player=2] tag=1068 value=0 
    TAG_CHANGE Entity=[entityName=Tribute from the Tides id=115 zone=PLAY zonePos=3 cardId=TRLA_154 player=2] tag=ZONE_POSITION value=0 
    TAG_CHANGE Entity=[entityName=Tribute from the Tides id=115 zone=PLAY zonePos=3 cardId=TRLA_154 player=2] tag=ZONE value=GRAVEYARD 
    TAG_CHANGE Entity=Zentimo tag=NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_TURN value=1 
    TAG_CHANGE Entity=Zentimo tag=NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_GAME value=1 
    HIDE_ENTITY - Entity=[entityName=Primal Talisman id=211 zone=PLAY zonePos=0 cardId=LOOT_344e player=2] tag=ZONE value=PLAY
    TAG_CHANGE Entity=[entityName=Primal Talisman id=211 zone=PLAY zonePos=0 cardId=LOOT_344e player=2] tag=ZONE value=REMOVEDFROMGAME 
    TAG_CHANGE Entity=[entityName=Tribute from the Tides id=115 zone=PLAY zonePos=3 cardId=TRLA_154 player=2] tag=DAMAGE value=0 
BLOCK_END
```

With the zone position updates and a couple other tags related to attacks removed for easy comparison, the only difference is the DEATHRATTLE tag not changing. The Shrine only acquired that tag once Primal Talismans was played (it didn't have it all along):

```
BLOCK_START BlockType=POWER Entity=[entityName=Primal Talismans id=207 zone=PLAY zonePos=0 cardId=LOOT_344 player=2] EffectCardId= EffectIndex=0 Target=0 SubOption=-1 
    TAG_CHANGE Entity=[entityName=Tribute from the Tides id=115 zone=PLAY zonePos=3 cardId=TRLA_154 player=2] tag=DEATHRATTLE value=1 
```

And Shrines all have the `InvisibleDeathrattle` tag, like what Silverware Golem has. I'm thinking `InvisibleDeathrattle` tag + added Deathrattle may be the cause.

Would be a good idea to re-test this, but adding a Deathrattle to the Silverware Golem before killing it.

**Comment by FireSiku** [comment] 2019-02-01 05:37
![image](https://user-images.githubusercontent.com/6915139/52104713-dbe66e00-25b9-11e9-9183-6bcb40ba3d53.png)

Managed to recreate it, steps that were taken in that game:
1) Get Silverware Golem on the board through Mind Games (probably good through any means)
2) Give him a deathrattle effect
3) Kill him and play Twilight's Call.
You're now the owner of a 1/1 Silverware Golem.

**Comment by FireSiku** [comment] 2019-02-01 10:03
Here's some other scenarios I tried. Did the steps again, then I played N'zoth followed immediately by Twilight's Call. Results are interesting
![image](https://user-images.githubusercontent.com/6915139/52116018-1a8e1f80-25de-11e9-94c4-c5a32f8d9364.png)

If you use Seance to get a new copy of a Silverwear Golem with a deathrattle effect, nothing happens and you just have a new copy of the card. But if you bounce it back to your hand, it'll keep the tag
![image](https://user-images.githubusercontent.com/6915139/52116098-52956280-25de-11e9-904f-938a950c581e.png)
And no enchantments will appear when played:
![image](https://user-images.githubusercontent.com/6915139/52116107-5628e980-25de-11e9-989a-b87510f914d1.png)
If the cardd dies, the card will not be resummoned as it doesn't have any deathrattle effects attached to it despite having the flag turned on. Twilight Call will still give you a 1/1 though.

**Comment by Sunchy321** [comment] 2019-03-27 12:26
There is an example that Twillight's Call resurrents Violet Illusionist and Lorewalker Cho, but neither of them has the InvisibleDeathrattle tag.

![image](https://user-images.githubusercontent.com/9764820/55074019-240da280-50ca-11e9-92e1-fbed3303c603.png)

We have reproduced it twice on Monday. The logs show that when the enchantment giving deathrattle leaves the battlefield, it changes tag=1234 (it seems like tag=attached) and don't clear the deathrattle flag of minion.

(Another example)
```
BLOCK_START BlockType=DEATHS Entity=GameEntity EffectCardId= EffectIndex=0 Target=0 SubOption=-1 
   TAG_CHANGE Entity=[entityName=小精灵 id=41 zone=PLAY zonePos=1 cardId=CS2_231 player=2] tag=1068 value=4 
   TAG_CHANGE Entity=[entityName=小精灵 id=41 zone=PLAY zonePos=1 cardId=CS2_231 player=2] tag=1068 value=0 
   TAG_CHANGE Entity=[entityName=小精灵 id=41 zone=PLAY zonePos=1 cardId=CS2_231 player=2] tag=EXHAUSTED value=0 
   TAG_CHANGE Entity=[entityName=小精灵 id=38 zone=PLAY zonePos=3 cardId=CS2_231 player=2] tag=ZONE_POSITION value=2 
   TAG_CHANGE Entity=[entityName=游荡恶鬼 id=37 zone=PLAY zonePos=2 cardId=ICC_701 player=2] tag=ZONE_POSITION value=1 
   TAG_CHANGE Entity=[entityName=小精灵 id=41 zone=PLAY zonePos=1 cardId=CS2_231 player=2] tag=ZONE_POSITION value=0 
   TAG_CHANGE Entity=[entityName=小精灵 id=41 zone=PLAY zonePos=1 cardId=CS2_231 player=2] tag=ZONE value=GRAVEYARD 
   TAG_CHANGE Entity=[entityName=原始护身符 id=98 zone=PLAY zonePos=0 cardId=LOOT_344e player=2] tag=1234 value=41 
   HIDE_ENTITY - Entity=[entityName=原始护身符 id=98 zone=PLAY zonePos=0 cardId=LOOT_344e player=2] tag=ZONE value=PLAY
   TAG_CHANGE Entity=[entityName=原始护身符 id=98 zone=PLAY zonePos=0 cardId=LOOT_344e player=2] tag=ZONE value=REMOVEDFROMGAME 
   TAG_CHANGE Entity=[entityName=小精灵 id=41 zone=PLAY zonePos=1 cardId=CS2_231 player=2] tag=DAMAGE value=0 
BLOCK_END
```

**Comment by troggnostupidhs** [comment] 2019-03-27 14:12
Does not happen with Corpse Raiser
![Hearthstone Screenshot 03-27-19 10 08 17](https://user-images.githubusercontent.com/22508641/55082756-a5d4e000-5078-11e9-9e51-e54d2c41d417.png)
![Hearthstone Screenshot 03-27-19 10 08 48](https://user-images.githubusercontent.com/22508641/55082757-a5d4e000-5078-11e9-90b1-c021265f76ac.png)

Or Elixir of Hope
![Hearthstone Screenshot 03-27-19 10 02 35](https://user-images.githubusercontent.com/22508641/55082781-b1280b80-5078-11e9-94dc-39690012f26d.png)
![Hearthstone Screenshot 03-27-19 10 04 33](https://user-images.githubusercontent.com/22508641/55082782-b1c0a200-5078-11e9-81db-ab95146a851a.png)

**Comment by Sunchy321** [comment] 2019-03-29 12:33
We tested more than twenty times on Wednesday but all failed. Today we test again without any changing of deck and each test can reproduce this bug. I don't know why...

And similarly, silencing a minion with deathrattle will prevent it from resurrenting by Twillight's Call. In this test the tag=1234 also appears. The log is here.

[Power.log](https://github.com/HearthSim/hs-bugs/files/3022602/Power.log)

(The plugin shows an Obsidian Statue is in the graveyard)
![7EFB9CA3A182C162D8CDF51FA4962503](https://user-images.githubusercontent.com/9764820/55232733-5c93b480-5261-11e9-996a-ebcf66bfd5ba.jpg)

(Resurrenting of Alleycat and Tabbycat with Cybertech Chip, tested in today)
![3DA1DE3B76FF092100B73782BF6B73B8](https://user-images.githubusercontent.com/9764820/55232742-64535900-5261-11e9-930f-1dd4d3044e63.jpg)

**Comment by Jetz72** [comment] 2019-03-29 13:07
The nature of the added Deathrattle appears relevant. A Deathrattle that returns the minion to the hand or sends it to some other zone will evidently not exhibit the bug.

**Comment by Jetz72** [comment] 2019-03-29 18:38
Another report, this time that Elixir of Hope did work. Minion was Curious Glimmerroot.
https://us.forums.blizzard.com/en/hearthstone/t/deathrattle-bug/1924
>I wanted to report a bug I had yesterday. It occured after I casted unindentified elixir(with the deathrattle effect that moves the card back to your hand) on a curious glimmeroot during the Un’goro-Frozen Throne-Kobolds Brawl. A few turns after my glimmeroot died, it had been summoned back with my Twilight’s call spell.

**Comment by troggnostupidhs** [comment] 2019-03-30 20:31
https://us.forums.blizzard.com/en/hearthstone/t/silenced-deathrattle-minion-not-coming-back-with-twilights-call/1992

> Silenced deathrattle minion not coming back with Twilight’s Call
> Here is a clip of it: https://hsreplay.net/replay/cei63xzrNJ8tyQxukAi5nG
> He silenced my loot hoarder and it did not come back after dying.

**Comment by Jetz72** [comment] 2019-04-01 15:20
https://www.reddit.com/r/hearthstone/comments/b7nar0/twilights_call_can_summon_minions_that_had_big/
>Twilight's Call can summon minions that had Big Bad Voodoo on them

https://www.reddit.com/r/hearthstone/comments/b4zosv/til_northshire_cleric_is_a_deathrattle_minion/
>![](https://i.redd.it/gdlruivu14o21.png)

https://www.reddit.com/r/hearthstone/comments/b4zosv/til_northshire_cleric_is_a_deathrattle_minion/ejbtiga/
>I just tried this in all variations. Could not reproduce
Northshire, hit her with Elixir of Hope, I copy her with Mirage Caller, the copy dies, I cast ilight's Call. Nothing happens
Another test: Northshire gets a Deathrattle by [[Corpse Raiser]], dies I cast Twilight's Call: Nothing happens.
Another: Hit Northshire with Elixir, kill it, Twilight, nothing happened.

With the recent spike in reports, it seems very likely that something changed recently to make this more common. Not sure what the pattern is though. Dominant player? Minion started in deck vs generated mid-game? Something else the minion gets subjected to before it dies?

**Comment by troggnostupidhs** [comment] 2019-04-04 20:14
https://www.reddit.com/r/hearthstone/comments/b9hixi/is_this_a_bug_i_wouldnt_have_thought_twilights/

![image](https://user-images.githubusercontent.com/22508641/55585457-b5959980-56f4-11e9-92bb-102a042e2c96.png)

> Thanks for adding it there - I knew I had seen issues with it before, but hadn't seen Myra specifically. If it helps, I had picked [[Gilded Gargoyle]] for her, since I see there's some comments about it mattering what type of deathrattle it was.

**Comment by troggnostupidhs** [comment] 2019-04-06 02:33
Currently unsure of the inconsistency. However, I tested for a dominant player issue and it did not change the results.

**Comment by troggnostupidhs** [comment] 2019-04-06 03:15
So far it seems to be related to dying from non-combat death.

If I traded the minions, they would not resurrect.

They did resurrect if they died from Shadow Word Death, regardless of who cast the spell.

Also, the elixir needs to grant deathrattle. The other elixirs didn't work.

![Hearthstone Screenshot 04-05-19 22 05 53](https://user-images.githubusercontent.com/22508641/55664159-cf6bd500-57f7-11e9-8f60-c9ebbfb93590.png)

AAEBAaCsAwAPWpAC3ALlBPIFigfTCuyuAvC7AuG/AtHBAtjBAtnBAqniAr/lAgA=

**Comment by troggnostupidhs** [comment] 2019-04-06 12:19
> Siku Yesterday at 11:55 PM
> Moat Lurker worked, so it's not limited to spells.

> Corpse Raiser Gurubashi Moat Lurker

![image](https://user-images.githubusercontent.com/22508641/55669387-afaece00-5844-11e9-9be7-134945fcdd33.png)

**Comment by troggnostupidhs** [comment] 2019-04-06 15:43
Tested with Jetz. This also happens if the minion dies by returning it to a full hand.

AAEBAaCsAwAPWpAC3AKTBOUE8gWKB+yuAvC7AuG/AtHBAtjBAp3PAqniAr/lAgA=

**Comment by troggnostupidhs** [comment] 2019-04-06 16:43
Also, the minion is resurrected when it dies to damage from a spell (eviscerate in the history). 

![Hearthstone Screenshot 04-06-19 12 09 28](https://user-images.githubusercontent.com/22508641/55672435-1e058780-5869-11e9-9e1b-aa19a2f0b3ea.png)

**Comment by troggnostupidhs** [comment] 2019-04-18 20:20
Another report for a silenced Death Rattle minion not reviving.

https://www.reddit.com/r/hearthstone/comments/bepae2/new_bug_silenced_minions_cant_be_revived_with/

![image](https://user-images.githubusercontent.com/22508641/56388642-83f0f800-61f5-11e9-9740-f207fc273d44.png)

![image](https://user-images.githubusercontent.com/22508641/56388655-8ce1c980-61f5-11e9-811b-78e2866e3275.png)

![image](https://user-images.githubusercontent.com/22508641/56388665-93704100-61f5-11e9-8a19-547d8a3f8175.png)

**Comment by troggnostupidhs** [comment] 2019-05-04 00:19
https://youtu.be/Gwidakw4i3k?t=123

https://youtu.be/Gwidakw4i3k?t=155

**Comment by troggnostupidhs** [comment] 2019-05-04 01:45
Latest tests with Jetz

Silenced Deathrattle
Attack - Not revived
Defend - Not revived
Spell - Not revived

AAEBAaCsAwT7Ae0F1cEC3sQCDZwCogK0AuUE8gW5BtcKt2zhvwLRwQLiygKp4gKm8AIA

Granted Deathrattle with Elixir and Corpse Raiser
Attack - Revived
Defend - Revived

AAEBAaCsAwAPnAK0ApME5QTyBasGuQa3bOG/AtHBAtjBAp3PAqniAr/lAqbwAgA=

**Comment by Jetz72** [comment] 2019-05-04 04:36
Best theory at this point seems to be that there was a server side change in the middle of our testing. Explains the weirdness @Sunchy321 encountered -
>We tested more than twenty times on Wednesday but all failed. Today we test again without any changing of deck and each test can reproduce this bug. I don't know why...

If there was an undocumented change that was gradually being rolled out to the servers, it'd account for the semi-random nature we experienced before, and why it's now evidently consistent across all cases. The Nat Pagle bug (#1140) shows that there's some amount of server changes going on without any warning. It was just as sudden when this bug seemingly changed its nature in the middle of patch 13.4.

It's something to keep in mind for strange test results going forward. Not all changes in behavior are necessarily gated by version changes or even hotfix announcements. Even changes like this can presumably happen silently overnight.

**Comment by troggnostupidhs** [comment] 2019-05-04 12:27
Blizzard acknowledged this a known issue on April 25th. 

https://us.forums.blizzard.com/en/hearthstone/t/known-issues-list-2019-updated-april-25th/64/6

>Twilight’s Call checks for minion that had an active Deathrattle effect at the time of death

**Comment by troggnostupidhs** [comment] 2019-05-14 17:40
https://playhearthstone.com/en-us/blog/22933721
> Fixed an issue where Twilight's Call would not resurrect Deathrattle minions that were silenced before dying.

> Fixed an issue where Twilight’s Call would resurrect cards that were granted a Deathrattle by cards like Soul of the Murloc but did not have an inherent Deathrattle effect.

**Closed** 2019-05-14 17:40 UTC
Labels: gameplay
