### ISSUE TITLE
Direct weapon destruction is always instantaneous instead of being queued

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#25] opened 2015-08-23 03:47 UTC
When Sabotage is used to destroy an enemy weapon and a minion, if both of them have Deathrattles, the weapon's Deathrattle always runs and resolves first, followed by the minion's, regardless of the play order of the weapon/minion. In the more general case, the weapon is destroyed first, before the minion is destroyed - this allows the minion's abilities to still trigger from the weapon's Deathrattle.
- [[Hearthstone Science] Sabotage, Death's Bite and Deathrattles](https://www.youtube.com/watch?v=5G-nBq7uAv4)
- [[Hearthstone Science] Grim Patron + Death's Bite vs Sabotage exceptional interaction ](https://www.youtube.com/watch?v=GDF_REINyKg)
- https://www.reddit.com/r/hearthstone/comments/32whz8/til_sabotage_destroy_weapon_first_and_then_minion/
- https://www.reddit.com/r/hearthstone/comments/2ni1w4/new_gvg_card_sabotage_epic_rogue_spell/cmdsgpt?context=10000

It is currently not clear if Sabotage destroying the weapon first is intended behavior, since the general expected behavior is that both weapon and minion should be destroyed at the same time, with their deaths processed in order of age. Ben Brode had said that "Things happen one after the other, but the one thing that never happens during a card resolution or trigger is minions dying." (see Reddit thread below) but did not explicitly mention weapons dying, only minions. From the interactions of Death's Bite attacking into a Harvest Golem, their Deathrattles will run in order of play, suggesting that weapon and minion deaths both follow the same general rules for death. From this, we can infer that the a sabotaged Death's Bite should not have triggered its Deathrattle before the death of the sabotaged minion.

**Comment by Patashu** [comment] 2015-08-24 03:50
The generalized form of this bug is that weapon destruction, unlike minion destruction, is not delayed until the end of the current outermost Phase via a mechanism like TO_BE_DESTROYED/'pending destroy'. Rather, it happens immediately inside of the Phase. Notably, weapon destruction due to durability loss occurs in order of play during the next Death Phase (for example if you finish your Death's Bite off into a Haunted Creeper, the first played is the first that triggers).

http://hearthstone.gamepedia.com/Advanced_rulebook#Instant_weapon_destruction

**Comment by Patashu** [comment] 2015-11-21 22:56
This needs to be re-tested.

https://www.youtube.com/watch?v=U3Pv4jhJ9dk&feature=youtu.be

Watch in this video - the Death's Bite Deathrattle does not activate between the two Harrison Jones activation, but waits until the end.

**Comment by Patashu** [comment] 2015-11-22 05:45
In contradiction to the above interaction, confirmed in 4.0:

https://www.youtube.com/watch?v=VhefmKhXt_o

**Comment by Patashu** [comment] 2016-04-08 06:59
https://www.youtube.com/watch?v=MBGr5sEu0x8&t=3m00s happened to kibler today, with armorsmith, death's bite and sabotage

**Comment by Patashu** [comment] 2016-05-07 12:04
The Grim Patron, Death's Bite, Sabotage interaction will be fixed because pending destroy Grim Patrons no longer summon a new Patron as of Patch 5.0. But the general bug (of destroyed weapons triggering their deathrattles at the Weapon Update Step rather than in the next Death Phase) is not fixed yet.

**Comment by VoidMayonnaise** [comment] 2017-06-12 17:20
https://youtu.be/PRE1UXjl_Dk
Retest in patch 8.2. Still working.

**Comment by Kybxd** [comment] 2017-08-13 12:12
This is fixed in 9.0. Brann + Gluttonous Ooze/Harrison will gain twice armor / draw twice cards.
Here is a test of Cursed Blade, Abomination and Sabotage.
* https://youtu.be/lXzAxXG-YK0

I also tested Brann + Blingtron, and the first weapon's deathrattle is still neglected.

**Closed** 2017-08-13 15:15 UTC
Labels: gameplay
