### ISSUE TITLE
Nat Pagle's animation repeats if interrupted by fatigue

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#83] opened 2015-08-24 06:08 UTC
If Nat Pagle triggers at the start of turn and draws into a Flame Leviathan or Fatigue damage, Nat Pagle's lightning icon visibly triggers but is interrupted by Flame Leviathan dealing 2 damage to all minions (or the Fatigue Damage animation), followed by Nat Pagle's lightning icon visibly triggering again, drawing another card. The second draw is actually the normal draw for the turn, so this bug is only visual in that Nat Pagle should not have visibly triggered a second time.

http://us.battle.net/hearthstone/en/forum/topic/15699454252
http://us.battle.net/hearthstone/en/forum/topic/16858636432
https://www.youtube.com/watch?v=4ayt4MraZVU&t=45s

**Comment by Patashu** [comment] 2015-08-24 06:08
This hasn't been confirmed since April 2015.

**Comment by jleclanche** [comment] 2015-08-30 08:57
TBH I think this is #11

**Comment by jleclanche** [comment] 2015-11-15 09:50
Dupe of #11.

**Closed by jleclanche** 2015-11-15 09:50 UTC
Labels: duplicate
