### ISSUE TITLE
Psychic Scream with Nozdormu on board

### ISSUE THREAD

**Issue by ruthnaebeck** [HearthSim/hs-bugs#885] opened 2018-01-06 05:44 UTC
After using Psychic Scream with Nozdormu on board, the cloudy fog doesn't dissipate

Here's a clip of the fog after the fact:
https://clips.twitch.tv/AnimatedAbstruseDelicataSuperVinlin

**Comment by troggnostupidhs** [comment] 2018-01-06 16:54
Thanks for the report! 

This is a duplicate of #214

**Closed by troggnostupidhs** 2018-01-06 16:54 UTC
