### ISSUE TITLE
Alexstrasza or Amara cannot work on Repentance Jaraxxus

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#795] opened 2017-08-22 05:01 UTC
http://www.bilibili.com/video/av13474746/

Jaraxxus would always stay at 1 health.

**Comment by troggnostupidhs** [comment] 2017-08-22 15:13
YouTube mirror. Interaction at 2:22 and 5:39.

https://www.youtube.com/watch?v=RT7fJzhAivk

**Comment by troggnostupidhs** [comment] 2017-10-17 20:16
Possibly mitigated

https://playhearthstone.com/en-us/blog/21098848

> Lord Jaraxxus no longer triggers Repentance, Sacred Trial, and Snipe.

**Comment by troggnostupidhs** [comment] 2017-10-19 01:57
Closing this issue because the reproduction case was removed

**Closed by troggnostupidhs** 2017-10-19 01:57 UTC
Labels: gameplay
