### ISSUE TITLE
Charge minions can't be played on the turn used.

### ISSUE THREAD

**Issue by Vedney** [HearthSim/hs-bugs#173] opened 2015-10-20 02:06 UTC
Sometimes when I play Al'Akir or Korkon Elite, mouse clicks through them as if they aren't there.

**Comment by Patashu** [comment] 2015-10-20 02:34
Duplicate of https://github.com/HearthSim/hs-bugs/issues/160 , closing

**Closed by Patashu** 2015-10-20 02:34 UTC
