### ISSUE TITLE
Blade Flurry with 0 Attack Gorehowl ignores Spell Damage

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#357] opened 2016-01-16 01:04 UTC
If you use Blade Flurry while having Gorehowl equipped and reduced to 0 attack the AoE effect will ignore Spell Damage so your opponents minions won't get damaged.
* https://www.youtube.com/watch?v=EPH2Y-xFUHI

This is inconsistent with Shadowflame, Shield Slam, Savagery and Lightbomb.

**Comment by astradamus** [comment] 2016-03-07 21:55
Is this maybe not a bug? +Spell Damage only increases damage on spells that deal damage. I can't think of any other way to test this, but it stands to reason that a variable damage spell that deals 0 damage would not benefit from +Spell Damage?

**Comment by Patashu** [comment] 2016-03-07 22:28
astradamus, there's a simple reason why this is a bug- Shadowflame on a 0 attack minion used to not be increased by Spell Damage +1, but it got fixed in patch 2.4.

I believe (but don't know for sure) that lightbomb + spell damage deals 1 damage to a 0 attack minion similarly.

**Comment by astradamus** [comment] 2016-03-07 23:02
Oh, I forgot Shadowflame. That's interesting. It seems more intuitive that you'd only benefit from +Spell Damage if you actually dealt damage.

Regarding Lightbomb, you're correct: https://www.youtube.com/watch?v=5lMJ_qOxIN4

**Comment by jleclanche** [comment] 2016-03-07 23:16
More specifically, spell damage is supposed to increase the *damage dealt by spells*. The bug determination comes from whether "blade flurry for 0" is "deal 0 damage" or "noop".

**Comment by astradamus** [comment] 2016-03-07 23:32
Put that way, I suppose it does make sense. The amount of the damage is separate from whether we're "doing an amount of damage." We're worried about the latter, not the former.

**Comment by culinko** [comment] 2016-04-25 16:41
This bug has been fixed.

**Closed by culinko** 2016-04-25 16:41 UTC
Labels: gameplay

**Comment by Patashu** [comment] 2016-05-06 05:07
[15:06] <culinko> ok so savagery and lightbomb both work correctly with 0 attack + spell damage (even with divine shields)
[15:06] <culinko> the only remaining test would be betrayal
