### ISSUE TITLE
Opponent's cards being shown on draw for no apparent reason

### ISSUE THREAD

**Issue by boynedmaster** [HearthSim/hs-bugs#768] opened 2017-06-28 20:41 UTC
https://www.youtube.com/watch?v=Sv-r39dc4mU&feature=youtu.be

In my Tavern Brawl match, every turn past Turn 3 had the opponent show his drawn card to me (Patches the Pirate).

I do not know of any circumstances to reproduce this bug.

**Comment by riQQ** [comment] 2017-06-28 21:45
Duplicate of #700.

**Closed** 2017-06-29 00:11 UTC
Labels: duplicate
