### ISSUE TITLE
Enter the Coliseum may cause a client hang

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#328] opened 2015-12-14 00:36 UTC
Under unknown circumstances, when your opponent plays Enter the Coliseum, the client will hang. (When this happens, the player must end the Hearthstone process and reconnect to continue playing.)

Occurences against The Steel Sentinel:
- https://www.reddit.com/r/hearthstone/comments/3wg5hy/interesting_bug_during_heroic_sentinel/
- http://us.battle.net/hearthstone/en/forum/topic/20044695844
- http://us.battle.net/hearthstone/en/forum/topic/20042655786
- http://us.battle.net/hearthstone/en/forum/topic/20043025963
- http://us.battle.net/hearthstone/en/forum/topic/20418542066
- http://us.battle.net/hearthstone/en/forum/topic/20042695686

Occurrences outside of Solo Adventure mode with screenshots:
- http://us.battle.net/hearthstone/en/forum/topic/20353075378
- http://us.battle.net/hearthstone/en/forum/topic/18704215427
- http://us.battle.net/hearthstone/en/forum/topic/19021722167
- http://us.battle.net/hearthstone/en/forum/topic/18706413972
- http://us.battle.net/hearthstone/en/forum/topic/19072167713
- https://www.reddit.com/r/hearthstone/comments/4dhab2/enter_the_colliseum_bug/

Without screenshots but with text descriptions:
- http://us.battle.net/hearthstone/en-us/forum/topic/19288110093
- http://us.battle.net/hearthstone/en/forum/topic/20418711950

**Comment by Patashu** [comment] 2015-12-14 00:45
(The reason why I didn't tag this 'adventure' is because I believe this can happen whenever your opponent plays EtC, not just when The Steel Sentinel does. I've seen a lot of reports of EtC hangs but didn't save them because I thought they were disconnects.)

**Comment by Patashu** [comment] 2015-12-14 00:45
tweeted to @ywoo_dev: https://twitter.com/Patashu0/status/676201022717493248

**Comment by Patashu** [comment] 2015-12-28 08:29
http://us.battle.net/hearthstone/en/forum/topic/20353075378

Another EtC report

**Comment by culinko** [comment] 2015-12-28 15:44
One report has a Mal'ganis aura (maybe some other buffs too) and a Dreadsteed spawning after the spell resolved. Another report has buffed mechs with Hobgoblin, Clockwork Knight, Micro Machine (self buff) and a Lightspawn spawning after the spell resolved (Shredder drop). The newest report has a buffed Ogre Brute (with Cruel Taskmaster) and probably a buffed Volcanic Drake (sparkles visual effect). So the bug might be related to either the buffs/auras being cleared and then failed to be re-applied after the spell finishes, or minions spawning another minions (this one is unlikely, since the last report has Volcanic Drake and Ogre Brute which were on the board before). So I am pretty sure we can figure out why the hang happens, because I don't think it's related to Steel Sentinel at all.

**Comment by Patashu** [comment] 2015-12-28 22:30
If you can reproduce it it will be very useful information for fixing this hang (as old as TGT) once and for all.

**Comment by culinko** [comment] 2016-03-16 23:20
New report in 4.2: https://www.reddit.com/r/hearthstone/comments/4aq9v6/so_is_this_a_new_trolling_trend_or_a_genuine_bug/.

**Comment by Patashu** [comment] 2016-03-21 22:05
Another new report in 4.2:

http://us.battle.net/hearthstone/en/forum/topic/20742975112

With video:

https://youtu.be/WRZN7ixGPD0

**Comment by culinko** [comment] 2016-03-21 22:06
This catches the whole game (mobile): http://us.battle.net/hearthstone/en/forum/topic/20742975112.

**Comment by Patashu** [comment] 2016-04-05 23:42
https://www.reddit.com/r/hearthstone/comments/4dhab2/enter_the_colliseum_bug/ another new report

**Comment by Patashu** [comment] 2016-04-20 01:59
Confirmed in 4.3:

http://us.battle.net/hearthstone/en/forum/topic/20743224827

**Comment by cfinnegn** [comment] 2016-04-20 05:37
Hey, I made a post on the HS support forums earlier today that you can site as another occurance (in regular ranked play)

http://us.battle.net/hearthstone/en/forum/topic/20743224827?page=1#4

Link to screenshots is in a later comment in that thread, but here's a direct link to save you the trouble:

http://imgur.com/a/UnHbG

**Comment by cfinnegn** [comment] 2016-04-20 05:39
That battle.net support post was mine. I just finished updating it to include screenshots. Here's the direct link to save you the trouble: http://imgur.com/a/UnHbG

**Comment by troggnostupidhs** [comment] 2017-06-10 03:39
Tried to reproduce it with Dreadsteed on the board. There were no issues.

![hearthstone screenshot 06-09-17 23 30 41](https://user-images.githubusercontent.com/22508641/26999646-e2cceaf4-4d6c-11e7-9db5-7beaf2cf5e6d.png)

![hearthstone screenshot 06-09-17 23 30 45](https://user-images.githubusercontent.com/22508641/26999647-e4673784-4d6c-11e7-9ff2-d7ae0ce8219b.png)

**Comment by troggnostupidhs** [comment] 2017-06-10 03:40
https://www.reddit.com/r/hearthstone/comments/4dhab2/enter_the_colliseum_bug/

Last report I can find is from April 2016. Can this be closed?

**Comment by cfinnegn** [comment] 2017-06-10 03:49
I don't know how I got included in this email; those screenshots looks like
they're from the League of Explorers expansion (?), which I don't own, so
it couldn't have been me that sent in those screenshots to log the ticket.
Unless that screenshot is just someone from support trying to reproduce the
issue. My Reddit account is also nowhere in the thread you've linked in
this email.

On Jun 9, 2017 11:40 PM, "troggnostupidhs" <notifications@github.com> wrote:

https://www.reddit.com/r/hearthstone/comments/4dhab2/
enter_the_colliseum_bug/

Last report I can find is from April 2016. Can this be closed?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/HearthSim/hs-bugs/issues/328#issuecomment-307539358>,
or mute the thread

**Comment by troggnostupidhs** [comment] 2017-06-10 03:56
@cfinnegn 

You are on this issue from a previous comment you made to post screenshots.

My question is just a general question. I'm not sure if this can be easily reproduced, and it seems like it might be fixed. It wasn't specifically about what you posted.

**Comment by cfinnegn** [comment] 2017-06-10 04:10
Ok, I found my post in there now. Well I've never noticed the issue since,
but I also don't even own the card in question, so I suppose you can close
the report if there are no other objections, but I'd say I'm probably not
the best judge here.

**Comment by culinko** [comment] 2017-06-10 05:53
I have no idea if this issue has been fixed yet, but we haven't been able to reproduce it at the time it was verified as a bug, so it requires certain timing.

**Comment by troggnostupidhs** [comment] 2017-06-15 14:41
Closing since there haven't been any recent reports.

**Closed by troggnostupidhs** 2017-06-15 14:41 UTC
Labels: animations, crash/hang
