### ISSUE TITLE
Swipe runs on-damage triggers in the wrong order

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#219] opened 2015-11-07 04:00 UTC
Swipe works in 2 steps and therefore causes on-damage triggers to activate in this order (after all damage has occurred): The minion targeted, then all other minions in reverse order of play. The spell should work in 1 step and on-damage triggers should run in the order of the minions being played.

Blizzard works in 2 steps and will cause the new minions spawned by Imp Gang Boss and Grim Patron to also be frozen (but undamaged). It is currently clarified that this is not a bug, and that "the damage and freeze are separate events". This was not changed in Patch 2.7.0.9166 (Tavern Brawl patch).
* https://twitter.com/bdbrode/status/586016236128993281
* https://twitter.com/bdbrode/status/587972727425765377

**Comment by Patashu** [comment] 2016-05-12 06:59
What about Explosive Shot and Powershot? IIRC they used to resolve on-damage Events in the order middle/right/left. Took videos of it a long time ago. Did they get fixed?

**Comment by Patashu** [comment] 2016-05-12 07:01
Closing as duplicate of https://github.com/HearthSim/hs-bugs/issues/65

**Closed by Patashu** 2016-05-12 07:01 UTC
Labels: gameplay
