### ISSUE TITLE
C'Thun entering hand by a card effect doubles the animation

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#479] opened 2016-04-28 11:13 UTC
When C'Thun is drawn by a draw effect, the animation repeats afterwards. Both players see the bug. This is a dead giveaway that C'Thun was just drawn. Confirmed with Shield Block and with Sprint.
- https://www.youtube.com/watch?v=ffLnYWOR5Bg&t=8m30s
- https://www.reddit.com/r/hearthstone/comments/4gla6n/bug_shield_blocking_into_cthun_causes_the/
- https://www.youtube.com/watch?v=zorvJ5Q1N_0

Also happens with Golden Monkey:
- https://www.youtube.com/watch?v=79KVZOe-M0I&t=3m38s
- https://www.youtube.com/watch?v=rmTVgsTwz1o&t=673
- https://www.youtube.com/watch?v=j_LbUBBn0xs&t=13m13s

**Comment by Xinhuan** [comment] 2016-04-28 16:55
Are you sure the opponent sees the doubled animation? Neither the Reddit thread nor the video shows this from the opponent's point of view.

**Comment by Patashu** [comment] 2016-04-28 22:54
@Xinhuan I'm not sure, but in the past, whenever an animation has been interrupted by an on-draw trigger, the animation has repeated afterwards for both players, so I predict this will work the same way.

**Comment by Patashu** [comment] 2016-05-01 00:24
https://youtu.be/ffLnYWOR5Bg&t=8m30s

Found confirmation that the info leak exists for both players.

**Comment by culinko** [comment] 2016-05-14 12:19
My friend played Coldlight Oracle and he drew his 2 cards first, then I drew mine. He confirmed that he drew C'Thun from it after I asked him. (Normally, both players draw cards at the same time).

**Comment by Patashu** [comment] 2016-05-16 23:32
Unconfirmed: Golden Monkey creating a C'Thun in your hand might double the animation.

https://www.reddit.com/r/hearthstone/comments/4jldbj/golden_monkey_bug/

**Comment by jleclanche** [comment] 2016-05-17 00:02
Yeah it'd make sense.

**Comment by culinko** [comment] 2016-05-18 16:49
Confirmed with video here: https://www.reddit.com/r/hearthstone/comments/4jvlrp/golden_monkey_bug_with_cthun/.

Here is the opponent's POV: https://www.youtube.com/watch?v=j_LbUBBn0xs?t=13m13s.

**Comment by Patashu** [comment] 2016-06-08 13:02
Confirmed in 5.0.0.13030:

http://us.battle.net/hearthstone/en/forum/topic/20745175026

**Comment by Patashu** [comment] 2016-06-21 02:25
Also happens with Golden Monkey:

https://www.youtube.com/watch?v=79KVZOe-M0I&t=3m38s

**Comment by PattuX** [comment] 2016-07-07 18:36
Also happens with Vanish

https://youtu.be/qbvKHEALY9k?t=9m18s

**Comment by PattuX** [comment] 2016-08-03 20:04
Kind of fixed for Monkey? 

* https://youtu.be/71ZtjJuHXwU?t=8m57s

Blackwing tech still stays in hand after Nefarian already left. Might be related to C'Thun being the first legendary created by the transform effect.

**Comment by culinko** [comment] 2016-08-04 05:06
Yeah I it might be fixed for Golden Monkey, because there is no double animation in the video you linked. However, a bug is still there, so the opponent still knows that you got C'Thun (because you have 1 less card visually in hand for some time). So we might close this once other animations (Shield Block, Coldlight Oracle) have been tested, but open a new issue for C'Thun and Golden Monkey.

Let's compare the animation behavior before and after (I used this video to figure out how it worked: https://www.youtube.com/watch?v=rmTVgsTwz1o&t=673). Let's say you have 5 cards in hand after playing Golden Monkey and C'Thun will spawn on position 3.

**Before:**

* You play Golden Monkey
* **Animation plays**
* The original cards from positions 4 and 5 slide to position 1 and 2
* The new legendaries replacing original cards from positions 1 and 2 appear in position 3 and 4 (so you have only 4 cards in hand and opponent knows you got C'Thun)
* **Animation plays again**
* Legendaries from positions 4 and 5 move to positions 1 and 2 
* C'Thun appears in position 3
* The original cards finally transform into new legendaries and appear in positions 4 and 5

**After:**

* You play Golden Monkey
* The original cards from positions 4 and 5 slide to position 1 and 2
* The new legendaries replacing original cards from positions 1 and 2 appear in positions 3 and 4 (so you have only 4 cards in hand and opponent knows you got C'Thun)
* **Animation plays**
* Legendaries from positions 4 and 5 move to positions 1 and 2 
* C'Thun appears in position 3
* The original cards finally transform into new legendaries and appear in positions 4 and 5

**Comment by troggnostupidhs** [comment] 2017-11-15 20:42
Deck
AAEBAYO6Agb2BO0FhgmDrAKprwLJrwIMtAHtApsFiAfdCMQPgBLEFpK2AvW7AoHCApTQAgA=

Still happens with Sprint.

**Comment by troggnostupidhs** [comment] 2018-01-03 21:55
https://www.reddit.com/r/hearthstone/comments/7ns8y1/when_playing_against_druid_you_can_tell_if_they/

> If an opposing druid has a spellstone in hand and uses their hero power, the animation of the teeth will play twice. I don't think this should be a thing and is possibly a bug that should be fixed.

> It's also if Unidentified Maul drawn from Divine Favor, the animation of DF triggers twice.
Or Ghoul Infestor only comes into play after you've drawn Jasper Spellstone from UI.
It's maybe fine if your opponent can't see, but they can and know that you have specific unidentified card or spellstone.

**Comment by troggnostupidhs** [comment] 2018-11-03 20:48
This is possibly fixed. All of the old videos are down so I don't know what it used to look like. I'm going to try again with my opponent drawing.

**Comment by troggnostupidhs** [comment] 2018-11-06 00:17
Opponent's draw seems normal too. I think this is fixed.

**Closed** 2018-11-06 00:18 UTC
Labels: animations, info leak
