### ISSUE TITLE
Druid of the Swarm cannot receive buffs from Hobgoblin

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#819] opened 2017-10-18 03:26 UTC
> Druid of the Swarm now correctly receives buffs from Hobgoblin.

However, it still cannnot receive buffs exactly.
![a](https://user-images.githubusercontent.com/18246091/31699704-ebe086aa-b3f6-11e7-915b-4155f8b698c0.jpg)
![b](https://user-images.githubusercontent.com/18246091/31699706-edb709ea-b3f6-11e7-9a2c-25f4bb2ff34f.jpg)

The pre-transform minion can receive buffs.
![c](https://user-images.githubusercontent.com/18246091/31699717-0fc17a16-b3f7-11e7-93e6-e7f6ea2c5cfa.jpg)

**Comment by Patashu** [comment] 2017-10-18 11:04
I guess working as intended lol. Hobgoblin triggers before Battlecry and the Battlecry is self-transform.

**Comment by troggnostupidhs** [comment] 2017-10-20 14:08
I don't think we track issues that were untracked, but fixed in a release. Either way, it's fixed now.

**Closed by troggnostupidhs** 2017-10-20 14:08 UTC
Labels: gameplay
