### ISSUE TITLE
Crafting/disenchanting UI glitch

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#544] opened 2016-05-26 03:38 UTC
Crafting or disenchanting a card followed by quickly clicking in the background will make the crafting UI to remain displayed. You need to restart the client in order to fix this bug.
- https://www.youtube.com/watch?v=ZSmIAeyBTig
- https://www.youtube.com/watch?v=PhgO5ZAWVoI&t=3m54s

**Comment by troggnostupidhs** [comment] 2017-09-11 04:50
This might be fixed. I can't reproduce it when Disenchanting.

**Comment by culinko** [comment] 2017-09-11 09:54
I couldn't reproduce it myself at the time it was bugged, though. Not sure what exact timing is needed.

**Comment by troggnostupidhs** [comment] 2019-04-06 12:43
I am going to close this. We can reopen it if there are additional reports.

**Closed by troggnostupidhs** 2019-04-06 12:43 UTC
Labels: ui
