### ISSUE TITLE
If you play Unearthed Raptor and copy the deathrattle of Primalfin Champion, it can't copy the spells stored by the deathrattle

### ISSUE THREAD

**Issue by VoidMayonnaise** [HearthSim/hs-bugs#754] opened 2017-06-14 14:37 UTC
I mentioned this interaction at #737, but now I think this one should be more likely a bug. Found in 8.0, confirmed in 8.2.2.
https://youtu.be/-W0jdTE2ZxI
I played Adaptation on Primalfin Champion, then copied the deathrattle by Unearthed Raptor, and played Forbidden Healing on Raptor. When the Raptor was killed, it only gave you Forbidden Healing, no Adaptation. Seems that there's inconsistency between Primalfin Champion and Moat Lurker, since Unearthed Raptor can correctly copy Moat Lurker's deathrattle.

**Comment by mukhishver** [comment] 2017-08-22 04:22
Why would this be a bug? The wording of the deathrattle is all you need. "Deathrattle: Return any spells you cast on this minion to your hand"
Raptor copies the deathrattle.
The reason moat lurker works is also in the wording. "Deathrattle: Resummon it"
Resummon what? when the battlecry triggers it finishes the wording of the deathrattle. This interaction is not a bug.

**Comment by troggnostupidhs** [comment] 2017-08-22 14:55
I agree with @mukhishver

**Comment by troggnostupidhs** [comment] 2017-11-16 16:34
I'm closing this issue, I don't think it is a bug.

**Closed** 2017-11-16 16:35 UTC
Labels: invalid

**Comment by troggnostupidhs** [comment] 2018-02-09 03:00
Some interactions

https://www.youtube.com/watch?v=Vx-D0DrNHPU

**Comment by bbbbbbbbba** [comment] 2018-02-09 05:38
What happens if the Champion is killed when controlled by the Priest?

**Comment by troggnostupidhs** [comment] 2018-02-09 16:12
> What happens if the Champion is killed when controlled by the Priest?

In the situation in the video, they should only get a Mind Control (because they cast one to take control). It's been known that Primalfin only gives spells you cast (see the other info in this thread). What wasn't known is what happens through multiple copying steps, and that's what the video shows.
