### ISSUE TITLE
Silence working partially against Unidentified Elixir

### ISSUE THREAD

**Issue by TTCrackers** [HearthSim/hs-bugs#884] opened 2018-01-05 20:59 UTC
My opponent played Unidentified Elixir, Elixir of Purity: +2/+2 and divine shield and when I silenced it with Spellbreaker kept his divine shield. I don't know why?
![hearthstone screenshot 01-05-18 15 47 01](https://user-images.githubusercontent.com/28037684/34628145-58edc1c2-f231-11e7-8eca-2b156977dfb7.png)

**Comment by riQQ** [comment] 2018-01-05 22:13
Duplicate of #860

**Closed** 2018-01-06 16:55 UTC
Labels: duplicate
