### ISSUE TITLE
Fandral Staghelm + Starfall deals 7 damage to target minion, even if it is friendly

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#489] opened 2016-05-01 05:57 UTC
- https://www.youtube.com/watch?v=2Oe5vZ3TcxA&t=2m25s

Obviously if you target it on a friendly minion the friendly minion should take 5, not 7, since it isn't included in the 'and 2 to all enemy minions' part.

**Comment by jleclanche** [comment] 2016-05-01 09:48
This is probably not a bug.

I'm guessing the action is "Deal 7 damage to target, and 2 damage to all other enemy minions" to avoid double-dipping on spell damage and damage triggers (same reason swipe isn't "Deal 3 damage to a minion and 1 damage to all enemy minions").

There's a lot of ways in which the fandral effects differ slightly from actually picking both effects; if you start listing them all we'll probably be here a while :smile:

**Comment by VoidMayonnaise** [comment] 2017-06-13 14:52
https://youtu.be/91uvTnFhw8Q
Confirmed in 8.2.

**Comment by troggnostupidhs** [comment] 2017-08-09 04:49
This is fixed with the Fandral change. It deals 5 damage to the friendly minion, and 2 damage to the enemy minions. 

https://www.reddit.com/r/hearthstone/comments/6sg730/fandral_now_deals_3_then_1_damage_with_wrath/

**Closed** 2017-08-09 04:50 UTC
Labels: gameplay
