### ISSUE TITLE
Malorne ignores deck size limit of 60

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#346] opened 2016-01-05 17:49 UTC
Your Deck has a limit of 60 cards.

This limit is respected by effects that generate new cards in your deck (Gang Up, Recycle, Ancient Shade, Elise Starseeker, Map to the Golden Monkey, Excavated Evil, Iron Juggernaut, Forgotten Torch, Beneath the Grounds). Even the Blackheart's Treasure Tavern Brawl (Issue #267) respects it when trying to insert cards into your deck at start of turn.
- https://www.youtube.com/watch?v=0inT1k2RHVY (Iron Juggernaut)
- https://www.youtube.com/watch?v=Y2Id0-v2anw (Forgotten Torch)
- https://www.youtube.com/watch?v=LVB1g3sjSLQ (Beneath the Grounds)

This limit is not respected by effects that move a card directly to your deck (Entomb, Malorne).
- https://www.youtube.com/watch?v=zzH0jVLQY4k (Entomb).
- https://www.youtube.com/watch?v=P295P-Zb3tw (Malorne)

**Update for Patch 7.0:**
Entomb has been fixed, Malorne is still bugged (see comments below).

**Comment by jleclanche** [comment] 2016-01-06 17:57
This is not a bug you can file, the 60-card deck limit is completely unofficial.

**Comment by Xinhuan** [comment] 2016-01-07 03:41
Even so, it is still inconsistent that some cards respect the limit, and some cards don't.

**Comment by culinko** [comment] 2016-01-25 19:11
We tested the remaining effects with SimFri, only Malorne bypassed the deck limit of 60 cards.

* https://www.youtube.com/watch?v=P295P-Zb3tw (Malorne)
* https://www.youtube.com/watch?v=0inT1k2RHVY (Iron Juggernaut)
* https://www.youtube.com/watch?v=Y2Id0-v2anw (Forgotten Torch)
* https://www.youtube.com/watch?v=LVB1g3sjSLQ (Beneath the Grounds)

**Comment by Patashu** [comment] 2016-12-06 00:51
/u/syricon tested this in Patch 7.0 with Weasel Tunneler. Weasel Tunneler obeys the 60 card limit. Assuming this card works like Malorne and Entomb does, then that means that this bug is fixed.

**Comment by culinko** [comment] 2017-02-25 20:04
I re-tested this to be sure and found out that Malorne is still not fixed in 7.0. Entomb and Weasel Tunneler work correctly and obey the deck limit. In both cases (Entomb and Weasel Tunneler) the minion gets visually destroyed on the board and moved to graveyard (it uses same animation as return to hand effects + full hand). However, Weasel Tunneler will display his "digging into the deck" animation after he is destroyed even though he doesn't go to the deck at all. Should we create a ticket for it?

Malorne (bugged): https://gist.github.com/culinko/96bbb4f8e6190747e62b0b93cb218969
![hearthstone screenshot 02-23-17 14 37 58](https://cloud.githubusercontent.com/assets/11700272/23334376/2df3706a-fb9d-11e6-8404-f7c5cc315671.png)

Entomb (fixed): https://gist.github.com/culinko/9cee2a083fdc8f41a74f40468a6fadae

I also tested all 3 cases with Feign Death just in case and found out same results, Entomb and Weasel Tunneler are working fine but Malorne isn't.

**Comment by culinko** [comment] 2017-04-04 15:49
Tested this again in 7.1 and found one interesting thing. If you use Madam Goya and Malorne (with Illidan shenanigans) to have 61 cards in deck, she doesn't destroy the 61st card at all because she doesn't have a full check for deck zone -> deck zone. This bug will be irrelevant once Malorne is fixed, but it's good to know how things work.

**Comment by culinko** [comment] 2017-04-28 20:41
The bug has been fixed in recent patch. For some reason they changed Malorne (and Weasel Tunneler) so they work the "setaside" way now. The original minion goes to setaside and a new entity is created in deck. Interestingly, #56 and #313 remain fixed (tested all of it today).

**Closed by culinko** 2017-04-28 20:41 UTC
Labels: gameplay
