### ISSUE TITLE
Self-transformation minion(like Faceless Manipulator) would trigger Unlicensed Apothecary's effect twice

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#652] opened 2016-12-07 12:37 UTC
applied by Hearthstone china bug report froum：http://bbs.hs.blizzard.cn/forum.php?mod=viewthread&tid=426218&extra=page%3D2&mobile=2

**Comment by Patashu** [comment] 2016-12-07 20:43
This may be intended.

Reasoning:

Unlicensed Apothecary is a Summon Resolution Step trigger.

Minions transformed by a Battlecry participate in the Special Summon Resolution Step at the end of the After Summon Phase. Reason: So a Druid of the Claw turning into a Beast triggers Starving Buzzard, and many similar interactions.

As a result, Unlicensed Apothecary triggers for the pre-transform minion following the On Play Phase, and the post-transform minion in the Special Summon Resolution Step following the After Summon Phase.

http://hearthstone.gamepedia.com/Unlicensed_Apothecary#Notes

**Comment by troggnostupidhs** [comment] 2016-12-07 22:30
Is this related to https://github.com/HearthSim/hs-bugs/issues/257

**Comment by Patashu** [comment] 2016-12-07 22:43
Oh ya, good point, it is. Then it probably is a bug, and 257 and this should be fixed or bugged together. (When fixed, I should update the definition of 'Double safeguard' in the advanced rulebook, though figuring out the correct wording would be tricky. Something like 'Minions are not allowed to trigger twice on the same Event, or twice for the same played minion (even if it's transformed while played)'.

**Comment by Patashu** [comment] 2017-04-09 08:01
Confirmed in 8.0 by jseakle

**Comment by Kybxd** [comment] 2017-04-18 04:27
Transformation between Sherazin and seed also triggers this.

* https://youtu.be/UQ3JQOCoEhI

**Comment by Patashu** [comment] 2017-04-18 04:50
I'm surprised by the seed being summoned triggering Unlicensed Apothecary, because I thought statless permanents (like the seed and Nether Portal) weren't supposed to count as minions.

**Comment by troggnostupidhs** [comment] 2017-04-26 20:35
In the 'Servant of Yogg-Saron' Tryouts Tavern Brawl, transform minions will cast two spells

**Comment by troggnostupidhs** [comment] 2017-04-28 19:14
Possibly related to #727

**Comment by troggnostupidhs** [comment] 2017-09-19 16:10
This might be fixed.

https://www.reddit.com/r/hearthstone/comments/713kyr/complete_list_of_undocumented_changes_from_patch/

**Comment by troggnostupidhs** [comment] 2017-09-19 18:15
Deck
AAEBAf0GAu0Flr0CDjD7AZwCtAKTBLkGxAjMCN0PrRDwEc8W58EC980CAA==

![hearthstone screenshot 09-19-17 14 14 51](https://user-images.githubusercontent.com/22508641/30608024-0a9093f6-9d45-11e7-9e58-573eeefd726e.png)

![hearthstone screenshot 09-19-17 14 15 02](https://user-images.githubusercontent.com/22508641/30608027-0c8a9de6-9d45-11e7-8061-cb4dd5e34f23.png)

**Comment by troggnostupidhs** [comment] 2017-10-17 20:21
Possibly mitigated

https://playhearthstone.com/en-us/blog/21098848

> Unlicensed Apothecary now reads: “After you summon a minion, deal 5 damage to your hero.” It will no longer activate from any Evolve effects.

**Comment by troggnostupidhs** [comment] 2017-10-18 01:02
![img000](https://user-images.githubusercontent.com/22508641/31696346-81cdcebc-b37e-11e7-9e5c-8f9a578f5cfd.png)
![img001](https://user-images.githubusercontent.com/22508641/31696347-81da6302-b37e-11e7-8ac2-54cbe82a1d99.png)

**Closed by troggnostupidhs** 2017-10-18 01:02 UTC
Labels: gameplay, may be intended
